apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: my-cluster
  namespace: default
spec:
  clusterNetwork:
    apiServerPort: null
    pods:
      cidrBlocks:
      - 10.244.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: my-cluster-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: ScalewayCluster
    name: my-cluster
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: provider-id
          value: scaleway://instance/{{ ds.meta_data.zone }}/{{ ds.meta_data.id }}
        - name: cloud-provider
          value: external
        name: '{{ ds.meta_data.hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: provider-id
          value: scaleway://instance/{{ ds.meta_data.zone }}/{{ ds.meta_data.id }}
        - name: cloud-provider
          value: external
        name: '{{ ds.meta_data.hostname }}'
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: ScalewayMachineTemplate
        name: my-cluster-control-plane
  replicas: 3
  version: v1.34.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ScalewayCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  failureDomains:
  - fr-par-1
  projectID: dd8176ab-87de-4a5e-82b3-da4aa22d5a2b
  region: fr-par
  scalewaySecretName: my-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster
  namespace: default
stringData:
  SCW_ACCESS_KEY: SCW3C0DMBPVN808634YB
  SCW_SECRET_KEY: a9c33e33-3ca2-4950-9a57-ac39d5d0e01d
type: Opaque
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ScalewayMachineTemplate
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      commercialType: DEV1-S
      image:
        name: cluster-api-ubuntu-2404-v1.34.3
      publicNetwork:
        enableIPv4: true
      rootVolume:
        type: block
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  clusterName: my-cluster
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: my-cluster-md-0
      clusterName: my-cluster
      failureDomain: fr-par-1
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: ScalewayMachineTemplate
        name: my-cluster-md-0
      version: v1.34.3
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
          - name: provider-id
            value: scaleway://instance/{{ ds.meta_data.zone }}/{{ ds.meta_data.id
              }}
          - name: cloud-provider
            value: external
          name: '{{ ds.meta_data.hostname }}'
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ScalewayMachineTemplate
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      commercialType: DEV1-S
      image:
        name: cluster-api-ubuntu-2404-v1.34.3
      publicNetwork:
        enableIPv4: true
      rootVolume:
        type: block
