# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .applications_v1alpha1_k8s_release import *
from .capacity_v1_capacity_allowance import *
from .compute_v1_disk import *
from .compute_v1_disk_snapshot import *
from .compute_v1_filesystem import *
from .compute_v1_gpu_cluster import *
from .compute_v1_instance import *
from .compute_v1_nvl_instance_group import *
from .dns_v1_record import *
from .dns_v1_zone import *
from .get_applications_v1alpha1_k8s_release import *
from .get_capacity_v1_capacity_allowance import *
from .get_capacity_v1_capacity_block_group import *
from .get_compute_v1_disk import *
from .get_compute_v1_disk_snapshot import *
from .get_compute_v1_filesystem import *
from .get_compute_v1_gpu_cluster import *
from .get_compute_v1_image import *
from .get_compute_v1_instance import *
from .get_compute_v1_nvl_instance_group import *
from .get_dns_v1_record import *
from .get_dns_v1_zone import *
from .get_iam_v1_access_permit import *
from .get_iam_v1_auth_public_key import *
from .get_iam_v1_federated_credentials import *
from .get_iam_v1_federation import *
from .get_iam_v1_federation_certificate import *
from .get_iam_v1_group import *
from .get_iam_v1_group_membership import *
from .get_iam_v1_invitation import *
from .get_iam_v1_project import *
from .get_iam_v1_service_account import *
from .get_iam_v1_tenant import *
from .get_iam_v1_tenant_user_account import *
from .get_iam_v2_access_key import *
from .get_iam_v2_project import *
from .get_iam_v2_tenant import *
from .get_kms_v1_asymmetric_key import *
from .get_kms_v1_symmetric_key import *
from .get_mk8s_v1_cluster import *
from .get_mk8s_v1_node_group import *
from .get_mk8s_v1alpha1_cluster import *
from .get_mk8s_v1alpha1_node_group import *
from .get_msp_mlflow_v1alpha1_cluster import *
from .get_msp_postgresql_v1alpha1_cluster import *
from .get_mysterybox_v1_secret import *
from .get_mysterybox_v1_secret_payload_entry import *
from .get_mysterybox_v1_secret_version import *
from .get_parent_id import *
from .get_quotas_v1_quota_allowance import *
from .get_registry_v1_registry import *
from .get_storage_v1_bucket import *
from .get_storage_v1_transfer import *
from .get_storage_v1alpha1_transfer import *
from .get_tunnel_v1_tunnel import *
from .get_vpc_v1_allocation import *
from .get_vpc_v1_network import *
from .get_vpc_v1_pool import *
from .get_vpc_v1_route import *
from .get_vpc_v1_route_table import *
from .get_vpc_v1_security_group import *
from .get_vpc_v1_security_rule import *
from .get_vpc_v1_subnet import *
from .get_vpc_v1alpha1_allocation import *
from .get_vpc_v1alpha1_network import *
from .get_vpc_v1alpha1_pool import *
from .get_vpc_v1alpha1_scope import *
from .get_vpc_v1alpha1_subnet import *
from .hash import *
from .iam_v1_access_permit import *
from .iam_v1_auth_public_key import *
from .iam_v1_federated_credentials import *
from .iam_v1_federation import *
from .iam_v1_federation_certificate import *
from .iam_v1_group import *
from .iam_v1_group_membership import *
from .iam_v1_invitation import *
from .iam_v1_service_account import *
from .iam_v2_access_key import *
from .iam_v2_project import *
from .kms_v1_asymmetric_key import *
from .kms_v1_symmetric_key import *
from .mk8s_v1_cluster import *
from .mk8s_v1_node_group import *
from .mk8s_v1alpha1_cluster import *
from .mk8s_v1alpha1_node_group import *
from .msp_mlflow_v1alpha1_cluster import *
from .msp_postgresql_v1alpha1_cluster import *
from .mysterybox_v1_secret import *
from .mysterybox_v1_secret_version import *
from .provider import *
from .quotas_v1_quota_allowance import *
from .registry_v1_registry import *
from .storage_v1_bucket import *
from .storage_v1_transfer import *
from .storage_v1alpha1_transfer import *
from .tunnel_v1_tunnel import *
from .vpc_v1_allocation import *
from .vpc_v1_network import *
from .vpc_v1_pool import *
from .vpc_v1_route import *
from .vpc_v1_route_table import *
from .vpc_v1_security_group import *
from .vpc_v1_security_rule import *
from .vpc_v1_subnet import *
from .vpc_v1alpha1_allocation import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_nebius.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_nebius.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "nebius",
  "mod": "index/applicationsV1alpha1K8sRelease",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/applicationsV1alpha1K8sRelease:ApplicationsV1alpha1K8sRelease": "ApplicationsV1alpha1K8sRelease"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/capacityV1CapacityAllowance",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/capacityV1CapacityAllowance:CapacityV1CapacityAllowance": "CapacityV1CapacityAllowance"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/computeV1Disk",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/computeV1Disk:ComputeV1Disk": "ComputeV1Disk"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/computeV1DiskSnapshot",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/computeV1DiskSnapshot:ComputeV1DiskSnapshot": "ComputeV1DiskSnapshot"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/computeV1Filesystem",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/computeV1Filesystem:ComputeV1Filesystem": "ComputeV1Filesystem"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/computeV1GpuCluster",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/computeV1GpuCluster:ComputeV1GpuCluster": "ComputeV1GpuCluster"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/computeV1Instance",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/computeV1Instance:ComputeV1Instance": "ComputeV1Instance"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/computeV1NvlInstanceGroup",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/computeV1NvlInstanceGroup:ComputeV1NvlInstanceGroup": "ComputeV1NvlInstanceGroup"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/dnsV1Record",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/dnsV1Record:DnsV1Record": "DnsV1Record"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/dnsV1Zone",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/dnsV1Zone:DnsV1Zone": "DnsV1Zone"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/hash",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/hash:Hash": "Hash"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1AccessPermit",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1AccessPermit:IamV1AccessPermit": "IamV1AccessPermit"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1AuthPublicKey",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1AuthPublicKey:IamV1AuthPublicKey": "IamV1AuthPublicKey"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1FederatedCredentials",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1FederatedCredentials:IamV1FederatedCredentials": "IamV1FederatedCredentials"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1Federation",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1Federation:IamV1Federation": "IamV1Federation"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1FederationCertificate",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1FederationCertificate:IamV1FederationCertificate": "IamV1FederationCertificate"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1Group",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1Group:IamV1Group": "IamV1Group"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1GroupMembership",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1GroupMembership:IamV1GroupMembership": "IamV1GroupMembership"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1Invitation",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1Invitation:IamV1Invitation": "IamV1Invitation"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV1ServiceAccount",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV1ServiceAccount:IamV1ServiceAccount": "IamV1ServiceAccount"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV2AccessKey",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV2AccessKey:IamV2AccessKey": "IamV2AccessKey"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/iamV2Project",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/iamV2Project:IamV2Project": "IamV2Project"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/kmsV1AsymmetricKey",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/kmsV1AsymmetricKey:KmsV1AsymmetricKey": "KmsV1AsymmetricKey"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/kmsV1SymmetricKey",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/kmsV1SymmetricKey:KmsV1SymmetricKey": "KmsV1SymmetricKey"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mk8sV1Cluster",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mk8sV1Cluster:Mk8sV1Cluster": "Mk8sV1Cluster"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mk8sV1NodeGroup",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mk8sV1NodeGroup:Mk8sV1NodeGroup": "Mk8sV1NodeGroup"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mk8sV1alpha1Cluster",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mk8sV1alpha1Cluster:Mk8sV1alpha1Cluster": "Mk8sV1alpha1Cluster"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mk8sV1alpha1NodeGroup",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mk8sV1alpha1NodeGroup:Mk8sV1alpha1NodeGroup": "Mk8sV1alpha1NodeGroup"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mspMlflowV1alpha1Cluster",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mspMlflowV1alpha1Cluster:MspMlflowV1alpha1Cluster": "MspMlflowV1alpha1Cluster"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mspPostgresqlV1alpha1Cluster",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mspPostgresqlV1alpha1Cluster:MspPostgresqlV1alpha1Cluster": "MspPostgresqlV1alpha1Cluster"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mysteryboxV1Secret",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mysteryboxV1Secret:MysteryboxV1Secret": "MysteryboxV1Secret"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/mysteryboxV1SecretVersion",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/mysteryboxV1SecretVersion:MysteryboxV1SecretVersion": "MysteryboxV1SecretVersion"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/quotasV1QuotaAllowance",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/quotasV1QuotaAllowance:QuotasV1QuotaAllowance": "QuotasV1QuotaAllowance"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/registryV1Registry",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/registryV1Registry:RegistryV1Registry": "RegistryV1Registry"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/storageV1Bucket",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/storageV1Bucket:StorageV1Bucket": "StorageV1Bucket"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/storageV1Transfer",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/storageV1Transfer:StorageV1Transfer": "StorageV1Transfer"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/storageV1alpha1Transfer",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/storageV1alpha1Transfer:StorageV1alpha1Transfer": "StorageV1alpha1Transfer"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/tunnelV1Tunnel",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/tunnelV1Tunnel:TunnelV1Tunnel": "TunnelV1Tunnel"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1Allocation",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1Allocation:VpcV1Allocation": "VpcV1Allocation"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1Network",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1Network:VpcV1Network": "VpcV1Network"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1Pool",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1Pool:VpcV1Pool": "VpcV1Pool"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1Route",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1Route:VpcV1Route": "VpcV1Route"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1RouteTable",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1RouteTable:VpcV1RouteTable": "VpcV1RouteTable"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1SecurityGroup",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1SecurityGroup:VpcV1SecurityGroup": "VpcV1SecurityGroup"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1SecurityRule",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1SecurityRule:VpcV1SecurityRule": "VpcV1SecurityRule"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1Subnet",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1Subnet:VpcV1Subnet": "VpcV1Subnet"
  }
 },
 {
  "pkg": "nebius",
  "mod": "index/vpcV1alpha1Allocation",
  "fqn": "pulumi_nebius",
  "classes": {
   "nebius:index/vpcV1alpha1Allocation:VpcV1alpha1Allocation": "VpcV1alpha1Allocation"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "nebius",
  "token": "pulumi:providers:nebius",
  "fqn": "pulumi_nebius",
  "class": "Provider"
 }
]
"""
)
