# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ApplicationsV1alpha1K8sReleaseArgs', 'ApplicationsV1alpha1K8sRelease']

@pulumi.input_type
class ApplicationsV1alpha1K8sReleaseArgs:
    def __init__(__self__, *,
                 application_name: pulumi.Input[_builtins.str],
                 cluster_id: pulumi.Input[_builtins.str],
                 namespace: pulumi.Input[_builtins.str],
                 product_slug: pulumi.Input[_builtins.str],
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseMetadataArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 sensitive: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseSensitiveArgs']] = None,
                 set: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 values: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a ApplicationsV1alpha1K8sRelease resource.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input['ApplicationsV1alpha1K8sReleaseMetadataArgs'] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input['ApplicationsV1alpha1K8sReleaseSensitiveArgs'] sensitive: This object mirrors the structure of the resource, providing view on the resource's [write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only) fields. It is a preferred way to define such fields as they are not stored in the state file. To use any field in write-only mode, do not set it in the main resource, instead set it in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object. Setting the field in the main resource will overwrite the field in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object at merging.
        """
        pulumi.set(__self__, "application_name", application_name)
        pulumi.set(__self__, "cluster_id", cluster_id)
        pulumi.set(__self__, "namespace", namespace)
        pulumi.set(__self__, "product_slug", product_slug)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)
        if sensitive is not None:
            pulumi.set(__self__, "sensitive", sensitive)
        if set is not None:
            pulumi.set(__self__, "set", set)
        if values is not None:
            pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter(name="applicationName")
    def application_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "application_name")

    @application_name.setter
    def application_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "application_name", value)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter(name="productSlug")
    def product_slug(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "product_slug")

    @product_slug.setter
    def product_slug(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "product_slug", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseMetadataArgs']]:
        """
        :

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter
    def sensitive(self) -> pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseSensitiveArgs']]:
        """
        This object mirrors the structure of the resource, providing view on the resource's [write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only) fields. It is a preferred way to define such fields as they are not stored in the state file. To use any field in write-only mode, do not set it in the main resource, instead set it in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object. Setting the field in the main resource will overwrite the field in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object at merging.
        """
        return pulumi.get(self, "sensitive")

    @sensitive.setter
    def sensitive(self, value: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseSensitiveArgs']]):
        pulumi.set(self, "sensitive", value)

    @_builtins.property
    @pulumi.getter
    def set(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "set")

    @set.setter
    def set(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "set", value)

    @_builtins.property
    @pulumi.getter
    def values(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "values")

    @values.setter
    def values(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "values", value)


@pulumi.input_type
class _ApplicationsV1alpha1K8sReleaseState:
    def __init__(__self__, *,
                 application_name: pulumi.Input[Optional[_builtins.str]] = None,
                 cluster_id: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 labels_all: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseMetadataArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 product_slug: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_version: pulumi.Input[Optional[_builtins.float]] = None,
                 sensitive: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseSensitiveArgs']] = None,
                 set: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 status: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseStatusArgs']] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None,
                 values: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ApplicationsV1alpha1K8sRelease resources.

        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels_all: Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        :param pulumi.Input['ApplicationsV1alpha1K8sReleaseMetadataArgs'] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input['ApplicationsV1alpha1K8sReleaseSensitiveArgs'] sensitive: This object mirrors the structure of the resource, providing view on the resource's [write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only) fields. It is a preferred way to define such fields as they are not stored in the state file. To use any field in write-only mode, do not set it in the main resource, instead set it in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object. Setting the field in the main resource will overwrite the field in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object at merging.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        if application_name is not None:
            pulumi.set(__self__, "application_name", application_name)
        if cluster_id is not None:
            pulumi.set(__self__, "cluster_id", cluster_id)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if labels_all is not None:
            pulumi.set(__self__, "labels_all", labels_all)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)
        if product_slug is not None:
            pulumi.set(__self__, "product_slug", product_slug)
        if resource_version is not None:
            pulumi.set(__self__, "resource_version", resource_version)
        if sensitive is not None:
            pulumi.set(__self__, "sensitive", sensitive)
        if set is not None:
            pulumi.set(__self__, "set", set)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)
        if values is not None:
            pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter(name="applicationName")
    def application_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "application_name")

    @application_name.setter
    def application_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "application_name", value)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was created.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="labelsAll")
    def labels_all(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        """
        return pulumi.get(self, "labels_all")

    @labels_all.setter
    def labels_all(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels_all", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseMetadataArgs']]:
        """
        :

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter(name="productSlug")
    def product_slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "product_slug")

    @product_slug.setter
    def product_slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "product_slug", value)

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @resource_version.setter
    def resource_version(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "resource_version", value)

    @_builtins.property
    @pulumi.getter
    def sensitive(self) -> pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseSensitiveArgs']]:
        """
        This object mirrors the structure of the resource, providing view on the resource's [write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only) fields. It is a preferred way to define such fields as they are not stored in the state file. To use any field in write-only mode, do not set it in the main resource, instead set it in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object. Setting the field in the main resource will overwrite the field in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object at merging.
        """
        return pulumi.get(self, "sensitive")

    @sensitive.setter
    def sensitive(self, value: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseSensitiveArgs']]):
        pulumi.set(self, "sensitive", value)

    @_builtins.property
    @pulumi.getter
    def set(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "set")

    @set.setter
    def set(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "set", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseStatusArgs']]:
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional['ApplicationsV1alpha1K8sReleaseStatusArgs']]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was last updated.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)

    @_builtins.property
    @pulumi.getter
    def values(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "values")

    @values.setter
    def values(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "values", value)


@pulumi.type_token("nebius:index/applicationsV1alpha1K8sRelease:ApplicationsV1alpha1K8sRelease")
class ApplicationsV1alpha1K8sRelease(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 application_name: pulumi.Input[Optional[_builtins.str]] = None,
                 cluster_id: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional[Union['ApplicationsV1alpha1K8sReleaseMetadataArgs', 'ApplicationsV1alpha1K8sReleaseMetadataArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 product_slug: pulumi.Input[Optional[_builtins.str]] = None,
                 sensitive: pulumi.Input[Optional[Union['ApplicationsV1alpha1K8sReleaseSensitiveArgs', 'ApplicationsV1alpha1K8sReleaseSensitiveArgsDict']]] = None,
                 set: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 values: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ApplicationsV1alpha1K8sRelease resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Union['ApplicationsV1alpha1K8sReleaseMetadataArgs', 'ApplicationsV1alpha1K8sReleaseMetadataArgsDict']] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[Union['ApplicationsV1alpha1K8sReleaseSensitiveArgs', 'ApplicationsV1alpha1K8sReleaseSensitiveArgsDict']] sensitive: This object mirrors the structure of the resource, providing view on the resource's [write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only) fields. It is a preferred way to define such fields as they are not stored in the state file. To use any field in write-only mode, do not set it in the main resource, instead set it in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object. Setting the field in the main resource will overwrite the field in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object at merging.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApplicationsV1alpha1K8sReleaseArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ApplicationsV1alpha1K8sRelease resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ApplicationsV1alpha1K8sReleaseArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationsV1alpha1K8sReleaseArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 application_name: pulumi.Input[Optional[_builtins.str]] = None,
                 cluster_id: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional[Union['ApplicationsV1alpha1K8sReleaseMetadataArgs', 'ApplicationsV1alpha1K8sReleaseMetadataArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 product_slug: pulumi.Input[Optional[_builtins.str]] = None,
                 sensitive: pulumi.Input[Optional[Union['ApplicationsV1alpha1K8sReleaseSensitiveArgs', 'ApplicationsV1alpha1K8sReleaseSensitiveArgsDict']]] = None,
                 set: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 values: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationsV1alpha1K8sReleaseArgs.__new__(ApplicationsV1alpha1K8sReleaseArgs)

            if application_name is None and not opts.urn:
                raise TypeError("Missing required property 'application_name'")
            __props__.__dict__["application_name"] = application_name
            if cluster_id is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_id'")
            __props__.__dict__["cluster_id"] = cluster_id
            __props__.__dict__["labels"] = labels
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["name"] = name
            if namespace is None and not opts.urn:
                raise TypeError("Missing required property 'namespace'")
            __props__.__dict__["namespace"] = namespace
            __props__.__dict__["parent_id"] = parent_id
            if product_slug is None and not opts.urn:
                raise TypeError("Missing required property 'product_slug'")
            __props__.__dict__["product_slug"] = product_slug
            __props__.__dict__["sensitive"] = None if sensitive is None else pulumi.Output.secret(sensitive)
            __props__.__dict__["set"] = None if set is None else pulumi.Output.secret(set)
            __props__.__dict__["values"] = None if values is None else pulumi.Output.secret(values)
            __props__.__dict__["created_at"] = None
            __props__.__dict__["labels_all"] = None
            __props__.__dict__["resource_version"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["updated_at"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["sensitive", "set", "values"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ApplicationsV1alpha1K8sRelease, __self__).__init__(
            'nebius:index/applicationsV1alpha1K8sRelease:ApplicationsV1alpha1K8sRelease',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            application_name: pulumi.Input[Optional[_builtins.str]] = None,
            cluster_id: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            labels_all: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            metadata: pulumi.Input[Optional[Union['ApplicationsV1alpha1K8sReleaseMetadataArgs', 'ApplicationsV1alpha1K8sReleaseMetadataArgsDict']]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            namespace: pulumi.Input[Optional[_builtins.str]] = None,
            parent_id: pulumi.Input[Optional[_builtins.str]] = None,
            product_slug: pulumi.Input[Optional[_builtins.str]] = None,
            resource_version: pulumi.Input[Optional[_builtins.float]] = None,
            sensitive: pulumi.Input[Optional[Union['ApplicationsV1alpha1K8sReleaseSensitiveArgs', 'ApplicationsV1alpha1K8sReleaseSensitiveArgsDict']]] = None,
            set: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            status: pulumi.Input[Optional[Union['ApplicationsV1alpha1K8sReleaseStatusArgs', 'ApplicationsV1alpha1K8sReleaseStatusArgsDict']]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None,
            values: pulumi.Input[Optional[_builtins.str]] = None) -> 'ApplicationsV1alpha1K8sRelease':
        """
        Get an existing ApplicationsV1alpha1K8sRelease resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels_all: Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        :param pulumi.Input[Union['ApplicationsV1alpha1K8sReleaseMetadataArgs', 'ApplicationsV1alpha1K8sReleaseMetadataArgsDict']] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input[Union['ApplicationsV1alpha1K8sReleaseSensitiveArgs', 'ApplicationsV1alpha1K8sReleaseSensitiveArgsDict']] sensitive: This object mirrors the structure of the resource, providing view on the resource's [write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only) fields. It is a preferred way to define such fields as they are not stored in the state file. To use any field in write-only mode, do not set it in the main resource, instead set it in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object. Setting the field in the main resource will overwrite the field in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object at merging.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ApplicationsV1alpha1K8sReleaseState.__new__(_ApplicationsV1alpha1K8sReleaseState)

        __props__.__dict__["application_name"] = application_name
        __props__.__dict__["cluster_id"] = cluster_id
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["labels"] = labels
        __props__.__dict__["labels_all"] = labels_all
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["name"] = name
        __props__.__dict__["namespace"] = namespace
        __props__.__dict__["parent_id"] = parent_id
        __props__.__dict__["product_slug"] = product_slug
        __props__.__dict__["resource_version"] = resource_version
        __props__.__dict__["sensitive"] = sensitive
        __props__.__dict__["set"] = set
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        __props__.__dict__["values"] = values
        return ApplicationsV1alpha1K8sRelease(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="applicationName")
    def application_name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "application_name")

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "cluster_id")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was created.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="labelsAll")
    def labels_all(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        """
        return pulumi.get(self, "labels_all")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['outputs.ApplicationsV1alpha1K8sReleaseMetadata']:
        """
        :

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="productSlug")
    def product_slug(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "product_slug")

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> pulumi.Output[_builtins.float]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @_builtins.property
    @pulumi.getter
    def sensitive(self) -> pulumi.Output[Optional['outputs.ApplicationsV1alpha1K8sReleaseSensitive']]:
        """
        This object mirrors the structure of the resource, providing view on the resource's [write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only) fields. It is a preferred way to define such fields as they are not stored in the state file. To use any field in write-only mode, do not set it in the main resource, instead set it in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object. Setting the field in the main resource will overwrite the field in the <span pulumi-lang-nodejs="`sensitive`" pulumi-lang-dotnet="`Sensitive`" pulumi-lang-go="`sensitive`" pulumi-lang-python="`sensitive`" pulumi-lang-yaml="`sensitive`" pulumi-lang-java="`sensitive`" pulumi-lang-hcl="`sensitive`">`sensitive`</span> object at merging.
        """
        return pulumi.get(self, "sensitive")

    @_builtins.property
    @pulumi.getter
    def set(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "set")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output['outputs.ApplicationsV1alpha1K8sReleaseStatus']:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was last updated.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def values(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "values")

