# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetMspPostgresqlV1alpha1ClusterResult',
    'AwaitableGetMspPostgresqlV1alpha1ClusterResult',
    'get_msp_postgresql_v1alpha1_cluster',
    'get_msp_postgresql_v1alpha1_cluster_output',
]

@pulumi.output_type
class GetMspPostgresqlV1alpha1ClusterResult:
    """
    A collection of values returned by getMspPostgresqlV1alpha1Cluster.
    """
    def __init__(__self__, backup=None, bootstrap=None, config=None, created_at=None, description=None, id=None, labels=None, metadata=None, name=None, network_id=None, parent_id=None, resource_version=None, status=None, updated_at=None):
        if backup and not isinstance(backup, dict):
            raise TypeError("Expected argument 'backup' to be a dict")
        pulumi.set(__self__, "backup", backup)
        if bootstrap and not isinstance(bootstrap, dict):
            raise TypeError("Expected argument 'bootstrap' to be a dict")
        pulumi.set(__self__, "bootstrap", bootstrap)
        if config and not isinstance(config, dict):
            raise TypeError("Expected argument 'config' to be a dict")
        pulumi.set(__self__, "config", config)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if metadata and not isinstance(metadata, dict):
            raise TypeError("Expected argument 'metadata' to be a dict")
        pulumi.set(__self__, "metadata", metadata)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if network_id and not isinstance(network_id, str):
            raise TypeError("Expected argument 'network_id' to be a str")
        pulumi.set(__self__, "network_id", network_id)
        if parent_id and not isinstance(parent_id, str):
            raise TypeError("Expected argument 'parent_id' to be a str")
        pulumi.set(__self__, "parent_id", parent_id)
        if resource_version and not isinstance(resource_version, float):
            raise TypeError("Expected argument 'resource_version' to be a float")
        pulumi.set(__self__, "resource_version", resource_version)
        if status and not isinstance(status, dict):
            raise TypeError("Expected argument 'status' to be a dict")
        pulumi.set(__self__, "status", status)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter
    def backup(self) -> 'outputs.GetMspPostgresqlV1alpha1ClusterBackupResult':
        return pulumi.get(self, "backup")

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> 'outputs.GetMspPostgresqlV1alpha1ClusterBootstrapResult':
        return pulumi.get(self, "bootstrap")

    @_builtins.property
    @pulumi.getter
    def config(self) -> 'outputs.GetMspPostgresqlV1alpha1ClusterConfigResult':
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> 'outputs.GetMspPostgresqlV1alpha1ClusterMetadataResult':
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> _builtins.str:
        return pulumi.get(self, "network_id")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> _builtins.str:
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> _builtins.float:
        return pulumi.get(self, "resource_version")

    @_builtins.property
    @pulumi.getter
    def status(self) -> 'outputs.GetMspPostgresqlV1alpha1ClusterStatusResult':
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        return pulumi.get(self, "updated_at")


class AwaitableGetMspPostgresqlV1alpha1ClusterResult(GetMspPostgresqlV1alpha1ClusterResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMspPostgresqlV1alpha1ClusterResult(
            backup=self.backup,
            bootstrap=self.bootstrap,
            config=self.config,
            created_at=self.created_at,
            description=self.description,
            id=self.id,
            labels=self.labels,
            metadata=self.metadata,
            name=self.name,
            network_id=self.network_id,
            parent_id=self.parent_id,
            resource_version=self.resource_version,
            status=self.status,
            updated_at=self.updated_at)


def get_msp_postgresql_v1alpha1_cluster(id: Optional[_builtins.str] = None,
                                        name: Optional[_builtins.str] = None,
                                        parent_id: Optional[_builtins.str] = None,
                                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMspPostgresqlV1alpha1ClusterResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nebius:index/getMspPostgresqlV1alpha1Cluster:getMspPostgresqlV1alpha1Cluster', __args__, opts=opts, typ=GetMspPostgresqlV1alpha1ClusterResult, package_ref=_utilities.get_package()).value

    return AwaitableGetMspPostgresqlV1alpha1ClusterResult(
        backup=pulumi.get(__ret__, 'backup'),
        bootstrap=pulumi.get(__ret__, 'bootstrap'),
        config=pulumi.get(__ret__, 'config'),
        created_at=pulumi.get(__ret__, 'created_at'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        metadata=pulumi.get(__ret__, 'metadata'),
        name=pulumi.get(__ret__, 'name'),
        network_id=pulumi.get(__ret__, 'network_id'),
        parent_id=pulumi.get(__ret__, 'parent_id'),
        resource_version=pulumi.get(__ret__, 'resource_version'),
        status=pulumi.get(__ret__, 'status'),
        updated_at=pulumi.get(__ret__, 'updated_at'))
def get_msp_postgresql_v1alpha1_cluster_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               parent_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMspPostgresqlV1alpha1ClusterResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nebius:index/getMspPostgresqlV1alpha1Cluster:getMspPostgresqlV1alpha1Cluster', __args__, opts=opts, typ=GetMspPostgresqlV1alpha1ClusterResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetMspPostgresqlV1alpha1ClusterResult(
        backup=pulumi.get(__response__, 'backup'),
        bootstrap=pulumi.get(__response__, 'bootstrap'),
        config=pulumi.get(__response__, 'config'),
        created_at=pulumi.get(__response__, 'created_at'),
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        metadata=pulumi.get(__response__, 'metadata'),
        name=pulumi.get(__response__, 'name'),
        network_id=pulumi.get(__response__, 'network_id'),
        parent_id=pulumi.get(__response__, 'parent_id'),
        resource_version=pulumi.get(__response__, 'resource_version'),
        status=pulumi.get(__response__, 'status'),
        updated_at=pulumi.get(__response__, 'updated_at')))
