# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetMysteryboxV1SecretPayloadEntryResult',
    'AwaitableGetMysteryboxV1SecretPayloadEntryResult',
    'get_mysterybox_v1_secret_payload_entry',
    'get_mysterybox_v1_secret_payload_entry_output',
]

@pulumi.output_type
class GetMysteryboxV1SecretPayloadEntryResult:
    """
    A collection of values returned by getMysteryboxV1SecretPayloadEntry.
    """
    def __init__(__self__, data=None, key=None, secret_id=None, version_id=None):
        if data and not isinstance(data, dict):
            raise TypeError("Expected argument 'data' to be a dict")
        pulumi.set(__self__, "data", data)
        if key and not isinstance(key, str):
            raise TypeError("Expected argument 'key' to be a str")
        pulumi.set(__self__, "key", key)
        if secret_id and not isinstance(secret_id, str):
            raise TypeError("Expected argument 'secret_id' to be a str")
        pulumi.set(__self__, "secret_id", secret_id)
        if version_id and not isinstance(version_id, str):
            raise TypeError("Expected argument 'version_id' to be a str")
        pulumi.set(__self__, "version_id", version_id)

    @_builtins.property
    @pulumi.getter
    def data(self) -> 'outputs.GetMysteryboxV1SecretPayloadEntryDataResult':
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "secret_id")

    @_builtins.property
    @pulumi.getter(name="versionId")
    def version_id(self) -> _builtins.str:
        return pulumi.get(self, "version_id")


class AwaitableGetMysteryboxV1SecretPayloadEntryResult(GetMysteryboxV1SecretPayloadEntryResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMysteryboxV1SecretPayloadEntryResult(
            data=self.data,
            key=self.key,
            secret_id=self.secret_id,
            version_id=self.version_id)


def get_mysterybox_v1_secret_payload_entry(data: Optional[Union['GetMysteryboxV1SecretPayloadEntryDataArgs', 'GetMysteryboxV1SecretPayloadEntryDataArgsDict']] = None,
                                           key: Optional[_builtins.str] = None,
                                           secret_id: Optional[_builtins.str] = None,
                                           version_id: Optional[_builtins.str] = None,
                                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMysteryboxV1SecretPayloadEntryResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['data'] = data
    __args__['key'] = key
    __args__['secretId'] = secret_id
    __args__['versionId'] = version_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nebius:index/getMysteryboxV1SecretPayloadEntry:getMysteryboxV1SecretPayloadEntry', __args__, opts=opts, typ=GetMysteryboxV1SecretPayloadEntryResult, package_ref=_utilities.get_package()).value

    return AwaitableGetMysteryboxV1SecretPayloadEntryResult(
        data=pulumi.get(__ret__, 'data'),
        key=pulumi.get(__ret__, 'key'),
        secret_id=pulumi.get(__ret__, 'secret_id'),
        version_id=pulumi.get(__ret__, 'version_id'))
def get_mysterybox_v1_secret_payload_entry_output(data: pulumi.Input[Optional[Optional[Union['GetMysteryboxV1SecretPayloadEntryDataArgs', 'GetMysteryboxV1SecretPayloadEntryDataArgsDict']]]] = None,
                                                  key: pulumi.Input[Optional[_builtins.str]] = None,
                                                  secret_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                                  version_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMysteryboxV1SecretPayloadEntryResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['data'] = data
    __args__['key'] = key
    __args__['secretId'] = secret_id
    __args__['versionId'] = version_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nebius:index/getMysteryboxV1SecretPayloadEntry:getMysteryboxV1SecretPayloadEntry', __args__, opts=opts, typ=GetMysteryboxV1SecretPayloadEntryResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetMysteryboxV1SecretPayloadEntryResult(
        data=pulumi.get(__response__, 'data'),
        key=pulumi.get(__response__, 'key'),
        secret_id=pulumi.get(__response__, 'secret_id'),
        version_id=pulumi.get(__response__, 'version_id')))
