# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetMk8sV1NodeGroupResult',
    'AwaitableGetMk8sV1NodeGroupResult',
    'get_mk8s_v1_node_group',
    'get_mk8s_v1_node_group_output',
]

@pulumi.output_type
class GetMk8sV1NodeGroupResult:
    """
    A collection of values returned by getMk8sV1NodeGroup.
    """
    def __init__(__self__, auto_repair=None, autoscaling=None, created_at=None, fixed_node_count=None, id=None, labels=None, metadata=None, name=None, parent_id=None, resource_version=None, status=None, strategy=None, template=None, updated_at=None, version=None):
        if auto_repair and not isinstance(auto_repair, dict):
            raise TypeError("Expected argument 'auto_repair' to be a dict")
        pulumi.set(__self__, "auto_repair", auto_repair)
        if autoscaling and not isinstance(autoscaling, dict):
            raise TypeError("Expected argument 'autoscaling' to be a dict")
        pulumi.set(__self__, "autoscaling", autoscaling)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if fixed_node_count and not isinstance(fixed_node_count, float):
            raise TypeError("Expected argument 'fixed_node_count' to be a float")
        pulumi.set(__self__, "fixed_node_count", fixed_node_count)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if metadata and not isinstance(metadata, dict):
            raise TypeError("Expected argument 'metadata' to be a dict")
        pulumi.set(__self__, "metadata", metadata)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if parent_id and not isinstance(parent_id, str):
            raise TypeError("Expected argument 'parent_id' to be a str")
        pulumi.set(__self__, "parent_id", parent_id)
        if resource_version and not isinstance(resource_version, float):
            raise TypeError("Expected argument 'resource_version' to be a float")
        pulumi.set(__self__, "resource_version", resource_version)
        if status and not isinstance(status, dict):
            raise TypeError("Expected argument 'status' to be a dict")
        pulumi.set(__self__, "status", status)
        if strategy and not isinstance(strategy, dict):
            raise TypeError("Expected argument 'strategy' to be a dict")
        pulumi.set(__self__, "strategy", strategy)
        if template and not isinstance(template, dict):
            raise TypeError("Expected argument 'template' to be a dict")
        pulumi.set(__self__, "template", template)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="autoRepair")
    def auto_repair(self) -> 'outputs.GetMk8sV1NodeGroupAutoRepairResult':
        return pulumi.get(self, "auto_repair")

    @_builtins.property
    @pulumi.getter
    def autoscaling(self) -> 'outputs.GetMk8sV1NodeGroupAutoscalingResult':
        return pulumi.get(self, "autoscaling")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="fixedNodeCount")
    def fixed_node_count(self) -> _builtins.float:
        return pulumi.get(self, "fixed_node_count")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> 'outputs.GetMk8sV1NodeGroupMetadataResult':
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> _builtins.str:
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> _builtins.float:
        return pulumi.get(self, "resource_version")

    @_builtins.property
    @pulumi.getter
    def status(self) -> 'outputs.GetMk8sV1NodeGroupStatusResult':
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def strategy(self) -> 'outputs.GetMk8sV1NodeGroupStrategyResult':
        return pulumi.get(self, "strategy")

    @_builtins.property
    @pulumi.getter
    def template(self) -> 'outputs.GetMk8sV1NodeGroupTemplateResult':
        return pulumi.get(self, "template")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")


class AwaitableGetMk8sV1NodeGroupResult(GetMk8sV1NodeGroupResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMk8sV1NodeGroupResult(
            auto_repair=self.auto_repair,
            autoscaling=self.autoscaling,
            created_at=self.created_at,
            fixed_node_count=self.fixed_node_count,
            id=self.id,
            labels=self.labels,
            metadata=self.metadata,
            name=self.name,
            parent_id=self.parent_id,
            resource_version=self.resource_version,
            status=self.status,
            strategy=self.strategy,
            template=self.template,
            updated_at=self.updated_at,
            version=self.version)


def get_mk8s_v1_node_group(id: Optional[_builtins.str] = None,
                           name: Optional[_builtins.str] = None,
                           parent_id: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMk8sV1NodeGroupResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nebius:index/getMk8sV1NodeGroup:getMk8sV1NodeGroup', __args__, opts=opts, typ=GetMk8sV1NodeGroupResult, package_ref=_utilities.get_package()).value

    return AwaitableGetMk8sV1NodeGroupResult(
        auto_repair=pulumi.get(__ret__, 'auto_repair'),
        autoscaling=pulumi.get(__ret__, 'autoscaling'),
        created_at=pulumi.get(__ret__, 'created_at'),
        fixed_node_count=pulumi.get(__ret__, 'fixed_node_count'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        metadata=pulumi.get(__ret__, 'metadata'),
        name=pulumi.get(__ret__, 'name'),
        parent_id=pulumi.get(__ret__, 'parent_id'),
        resource_version=pulumi.get(__ret__, 'resource_version'),
        status=pulumi.get(__ret__, 'status'),
        strategy=pulumi.get(__ret__, 'strategy'),
        template=pulumi.get(__ret__, 'template'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        version=pulumi.get(__ret__, 'version'))
def get_mk8s_v1_node_group_output(id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  parent_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMk8sV1NodeGroupResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nebius:index/getMk8sV1NodeGroup:getMk8sV1NodeGroup', __args__, opts=opts, typ=GetMk8sV1NodeGroupResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetMk8sV1NodeGroupResult(
        auto_repair=pulumi.get(__response__, 'auto_repair'),
        autoscaling=pulumi.get(__response__, 'autoscaling'),
        created_at=pulumi.get(__response__, 'created_at'),
        fixed_node_count=pulumi.get(__response__, 'fixed_node_count'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        metadata=pulumi.get(__response__, 'metadata'),
        name=pulumi.get(__response__, 'name'),
        parent_id=pulumi.get(__response__, 'parent_id'),
        resource_version=pulumi.get(__response__, 'resource_version'),
        status=pulumi.get(__response__, 'status'),
        strategy=pulumi.get(__response__, 'strategy'),
        template=pulumi.get(__response__, 'template'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        version=pulumi.get(__response__, 'version')))
