# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIamV1FederatedCredentialsResult',
    'AwaitableGetIamV1FederatedCredentialsResult',
    'get_iam_v1_federated_credentials',
    'get_iam_v1_federated_credentials_output',
]

@pulumi.output_type
class GetIamV1FederatedCredentialsResult:
    """
    A collection of values returned by getIamV1FederatedCredentials.
    """
    def __init__(__self__, created_at=None, federated_subject_id=None, id=None, labels=None, metadata=None, name=None, oidc_provider=None, parent_id=None, resource_version=None, status=None, subject_id=None, updated_at=None):
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if federated_subject_id and not isinstance(federated_subject_id, str):
            raise TypeError("Expected argument 'federated_subject_id' to be a str")
        pulumi.set(__self__, "federated_subject_id", federated_subject_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if metadata and not isinstance(metadata, dict):
            raise TypeError("Expected argument 'metadata' to be a dict")
        pulumi.set(__self__, "metadata", metadata)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if oidc_provider and not isinstance(oidc_provider, dict):
            raise TypeError("Expected argument 'oidc_provider' to be a dict")
        pulumi.set(__self__, "oidc_provider", oidc_provider)
        if parent_id and not isinstance(parent_id, str):
            raise TypeError("Expected argument 'parent_id' to be a str")
        pulumi.set(__self__, "parent_id", parent_id)
        if resource_version and not isinstance(resource_version, float):
            raise TypeError("Expected argument 'resource_version' to be a float")
        pulumi.set(__self__, "resource_version", resource_version)
        if status and not isinstance(status, dict):
            raise TypeError("Expected argument 'status' to be a dict")
        pulumi.set(__self__, "status", status)
        if subject_id and not isinstance(subject_id, str):
            raise TypeError("Expected argument 'subject_id' to be a str")
        pulumi.set(__self__, "subject_id", subject_id)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="federatedSubjectId")
    def federated_subject_id(self) -> _builtins.str:
        return pulumi.get(self, "federated_subject_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> 'outputs.GetIamV1FederatedCredentialsMetadataResult':
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="oidcProvider")
    def oidc_provider(self) -> 'outputs.GetIamV1FederatedCredentialsOidcProviderResult':
        return pulumi.get(self, "oidc_provider")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> _builtins.str:
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> _builtins.float:
        return pulumi.get(self, "resource_version")

    @_builtins.property
    @pulumi.getter
    def status(self) -> 'outputs.GetIamV1FederatedCredentialsStatusResult':
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="subjectId")
    def subject_id(self) -> _builtins.str:
        return pulumi.get(self, "subject_id")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        return pulumi.get(self, "updated_at")


class AwaitableGetIamV1FederatedCredentialsResult(GetIamV1FederatedCredentialsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIamV1FederatedCredentialsResult(
            created_at=self.created_at,
            federated_subject_id=self.federated_subject_id,
            id=self.id,
            labels=self.labels,
            metadata=self.metadata,
            name=self.name,
            oidc_provider=self.oidc_provider,
            parent_id=self.parent_id,
            resource_version=self.resource_version,
            status=self.status,
            subject_id=self.subject_id,
            updated_at=self.updated_at)


def get_iam_v1_federated_credentials(id: Optional[_builtins.str] = None,
                                     name: Optional[_builtins.str] = None,
                                     parent_id: Optional[_builtins.str] = None,
                                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIamV1FederatedCredentialsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nebius:index/getIamV1FederatedCredentials:getIamV1FederatedCredentials', __args__, opts=opts, typ=GetIamV1FederatedCredentialsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetIamV1FederatedCredentialsResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        federated_subject_id=pulumi.get(__ret__, 'federated_subject_id'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        metadata=pulumi.get(__ret__, 'metadata'),
        name=pulumi.get(__ret__, 'name'),
        oidc_provider=pulumi.get(__ret__, 'oidc_provider'),
        parent_id=pulumi.get(__ret__, 'parent_id'),
        resource_version=pulumi.get(__ret__, 'resource_version'),
        status=pulumi.get(__ret__, 'status'),
        subject_id=pulumi.get(__ret__, 'subject_id'),
        updated_at=pulumi.get(__ret__, 'updated_at'))
def get_iam_v1_federated_credentials_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                            name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                            parent_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIamV1FederatedCredentialsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nebius:index/getIamV1FederatedCredentials:getIamV1FederatedCredentials', __args__, opts=opts, typ=GetIamV1FederatedCredentialsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetIamV1FederatedCredentialsResult(
        created_at=pulumi.get(__response__, 'created_at'),
        federated_subject_id=pulumi.get(__response__, 'federated_subject_id'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        metadata=pulumi.get(__response__, 'metadata'),
        name=pulumi.get(__response__, 'name'),
        oidc_provider=pulumi.get(__response__, 'oidc_provider'),
        parent_id=pulumi.get(__response__, 'parent_id'),
        resource_version=pulumi.get(__response__, 'resource_version'),
        status=pulumi.get(__response__, 'status'),
        subject_id=pulumi.get(__response__, 'subject_id'),
        updated_at=pulumi.get(__response__, 'updated_at')))
