# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['Mk8sV1ClusterArgs', 'Mk8sV1Cluster']

@pulumi.input_type
class Mk8sV1ClusterArgs:
    def __init__(__self__, *,
                 control_plane: pulumi.Input['Mk8sV1ClusterControlPlaneArgs'],
                 parent_id: pulumi.Input[_builtins.str],
                 kube_network: Optional[pulumi.Input['Mk8sV1ClusterKubeNetworkArgs']] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input['Mk8sV1ClusterMetadataArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Mk8sV1Cluster resource.

        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input['Mk8sV1ClusterKubeNetworkArgs'] kube_network: Defines kubernetes network configuration, like IP allocation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input['Mk8sV1ClusterMetadataArgs'] metadata: :
               
                  #### Inner value description
                  
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        """
        pulumi.set(__self__, "control_plane", control_plane)
        pulumi.set(__self__, "parent_id", parent_id)
        if kube_network is not None:
            pulumi.set(__self__, "kube_network", kube_network)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="controlPlane")
    def control_plane(self) -> pulumi.Input['Mk8sV1ClusterControlPlaneArgs']:
        return pulumi.get(self, "control_plane")

    @control_plane.setter
    def control_plane(self, value: pulumi.Input['Mk8sV1ClusterControlPlaneArgs']):
        pulumi.set(self, "control_plane", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Input[_builtins.str]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter(name="kubeNetwork")
    def kube_network(self) -> Optional[pulumi.Input['Mk8sV1ClusterKubeNetworkArgs']]:
        """
        Defines kubernetes network configuration, like IP allocation.
        """
        return pulumi.get(self, "kube_network")

    @kube_network.setter
    def kube_network(self, value: Optional[pulumi.Input['Mk8sV1ClusterKubeNetworkArgs']]):
        pulumi.set(self, "kube_network", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input['Mk8sV1ClusterMetadataArgs']]:
        """
        :

           #### Inner value description
           
           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input['Mk8sV1ClusterMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _Mk8sV1ClusterState:
    def __init__(__self__, *,
                 control_plane: Optional[pulumi.Input['Mk8sV1ClusterControlPlaneArgs']] = None,
                 created_at: Optional[pulumi.Input[_builtins.str]] = None,
                 kube_network: Optional[pulumi.Input['Mk8sV1ClusterKubeNetworkArgs']] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input['Mk8sV1ClusterMetadataArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 parent_id: Optional[pulumi.Input[_builtins.str]] = None,
                 resource_version: Optional[pulumi.Input[_builtins.float]] = None,
                 status: Optional[pulumi.Input['Mk8sV1ClusterStatusArgs']] = None,
                 updated_at: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Mk8sV1Cluster resources.

        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
                  
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input['Mk8sV1ClusterKubeNetworkArgs'] kube_network: Defines kubernetes network configuration, like IP allocation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input['Mk8sV1ClusterMetadataArgs'] metadata: :
               
                  #### Inner value description
                  
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
                  
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        if control_plane is not None:
            pulumi.set(__self__, "control_plane", control_plane)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if kube_network is not None:
            pulumi.set(__self__, "kube_network", kube_network)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)
        if resource_version is not None:
            pulumi.set(__self__, "resource_version", resource_version)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="controlPlane")
    def control_plane(self) -> Optional[pulumi.Input['Mk8sV1ClusterControlPlaneArgs']]:
        return pulumi.get(self, "control_plane")

    @control_plane.setter
    def control_plane(self, value: Optional[pulumi.Input['Mk8sV1ClusterControlPlaneArgs']]):
        pulumi.set(self, "control_plane", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was created.
           
           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="kubeNetwork")
    def kube_network(self) -> Optional[pulumi.Input['Mk8sV1ClusterKubeNetworkArgs']]:
        """
        Defines kubernetes network configuration, like IP allocation.
        """
        return pulumi.get(self, "kube_network")

    @kube_network.setter
    def kube_network(self, value: Optional[pulumi.Input['Mk8sV1ClusterKubeNetworkArgs']]):
        pulumi.set(self, "kube_network", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input['Mk8sV1ClusterMetadataArgs']]:
        """
        :

           #### Inner value description
           
           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input['Mk8sV1ClusterMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @resource_version.setter
    def resource_version(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "resource_version", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input['Mk8sV1ClusterStatusArgs']]:
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input['Mk8sV1ClusterStatusArgs']]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was last updated.
           
           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("nebius:index/mk8sV1Cluster:Mk8sV1Cluster")
class Mk8sV1Cluster(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 control_plane: Optional[pulumi.Input[Union['Mk8sV1ClusterControlPlaneArgs', 'Mk8sV1ClusterControlPlaneArgsDict']]] = None,
                 kube_network: Optional[pulumi.Input[Union['Mk8sV1ClusterKubeNetworkArgs', 'Mk8sV1ClusterKubeNetworkArgsDict']]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Union['Mk8sV1ClusterMetadataArgs', 'Mk8sV1ClusterMetadataArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 parent_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Mk8sV1Cluster resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['Mk8sV1ClusterKubeNetworkArgs', 'Mk8sV1ClusterKubeNetworkArgsDict']] kube_network: Defines kubernetes network configuration, like IP allocation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Union['Mk8sV1ClusterMetadataArgs', 'Mk8sV1ClusterMetadataArgsDict']] metadata: :
               
                  #### Inner value description
                  
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Mk8sV1ClusterArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Mk8sV1Cluster resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param Mk8sV1ClusterArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(Mk8sV1ClusterArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 control_plane: Optional[pulumi.Input[Union['Mk8sV1ClusterControlPlaneArgs', 'Mk8sV1ClusterControlPlaneArgsDict']]] = None,
                 kube_network: Optional[pulumi.Input[Union['Mk8sV1ClusterKubeNetworkArgs', 'Mk8sV1ClusterKubeNetworkArgsDict']]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Union['Mk8sV1ClusterMetadataArgs', 'Mk8sV1ClusterMetadataArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 parent_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = Mk8sV1ClusterArgs.__new__(Mk8sV1ClusterArgs)

            if control_plane is None and not opts.urn:
                raise TypeError("Missing required property 'control_plane'")
            __props__.__dict__["control_plane"] = control_plane
            __props__.__dict__["kube_network"] = kube_network
            __props__.__dict__["labels"] = labels
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["name"] = name
            if parent_id is None and not opts.urn:
                raise TypeError("Missing required property 'parent_id'")
            __props__.__dict__["parent_id"] = parent_id
            __props__.__dict__["created_at"] = None
            __props__.__dict__["resource_version"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["updated_at"] = None
        super(Mk8sV1Cluster, __self__).__init__(
            'nebius:index/mk8sV1Cluster:Mk8sV1Cluster',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            control_plane: Optional[pulumi.Input[Union['Mk8sV1ClusterControlPlaneArgs', 'Mk8sV1ClusterControlPlaneArgsDict']]] = None,
            created_at: Optional[pulumi.Input[_builtins.str]] = None,
            kube_network: Optional[pulumi.Input[Union['Mk8sV1ClusterKubeNetworkArgs', 'Mk8sV1ClusterKubeNetworkArgsDict']]] = None,
            labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            metadata: Optional[pulumi.Input[Union['Mk8sV1ClusterMetadataArgs', 'Mk8sV1ClusterMetadataArgsDict']]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            parent_id: Optional[pulumi.Input[_builtins.str]] = None,
            resource_version: Optional[pulumi.Input[_builtins.float]] = None,
            status: Optional[pulumi.Input[Union['Mk8sV1ClusterStatusArgs', 'Mk8sV1ClusterStatusArgsDict']]] = None,
            updated_at: Optional[pulumi.Input[_builtins.str]] = None) -> 'Mk8sV1Cluster':
        """
        Get an existing Mk8sV1Cluster resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
                  
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[Union['Mk8sV1ClusterKubeNetworkArgs', 'Mk8sV1ClusterKubeNetworkArgsDict']] kube_network: Defines kubernetes network configuration, like IP allocation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Union['Mk8sV1ClusterMetadataArgs', 'Mk8sV1ClusterMetadataArgsDict']] metadata: :
               
                  #### Inner value description
                  
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
                  
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _Mk8sV1ClusterState.__new__(_Mk8sV1ClusterState)

        __props__.__dict__["control_plane"] = control_plane
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["kube_network"] = kube_network
        __props__.__dict__["labels"] = labels
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["name"] = name
        __props__.__dict__["parent_id"] = parent_id
        __props__.__dict__["resource_version"] = resource_version
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        return Mk8sV1Cluster(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="controlPlane")
    def control_plane(self) -> pulumi.Output['outputs.Mk8sV1ClusterControlPlane']:
        return pulumi.get(self, "control_plane")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was created.
           
           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="kubeNetwork")
    def kube_network(self) -> pulumi.Output[Optional['outputs.Mk8sV1ClusterKubeNetwork']]:
        """
        Defines kubernetes network configuration, like IP allocation.
        """
        return pulumi.get(self, "kube_network")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['outputs.Mk8sV1ClusterMetadata']:
        """
        :

           #### Inner value description
           
           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> pulumi.Output[_builtins.float]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output['outputs.Mk8sV1ClusterStatus']:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was last updated.
           
           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

