# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['StorageV1BucketArgs', 'StorageV1Bucket']

@pulumi.input_type
class StorageV1BucketArgs:
    def __init__(__self__, *,
                 bucket_policy: pulumi.Input[Optional['StorageV1BucketBucketPolicyArgs']] = None,
                 cors: pulumi.Input[Optional['StorageV1BucketCorsArgs']] = None,
                 default_storage_class: pulumi.Input[Optional[_builtins.str]] = None,
                 force_storage_class: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 lifecycle_configuration: pulumi.Input[Optional['StorageV1BucketLifecycleConfigurationArgs']] = None,
                 max_size_bytes: pulumi.Input[Optional[_builtins.float]] = None,
                 metadata: pulumi.Input[Optional['StorageV1BucketMetadataArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 object_audit_logging: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 versioning_policy: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a StorageV1Bucket resource.

        :param pulumi.Input['StorageV1BucketBucketPolicyArgs'] bucket_policy: :
               
                  Bucket policy specifies granular permissions for a bucket.
               
               #### Inner value description
               
                  Bucket policy specifies granular permissions for a bucket.
        :param pulumi.Input['StorageV1BucketCorsArgs'] cors: :
               
                  Cross-origin resource sharing configuration.
               
               #### Inner value description
               
                  Cross-origin resource sharing (CORS) configuration.
        :param pulumi.Input[_builtins.str] default_storage_class: :
               
                  Storage class to use by default for uploads to the bucket. It may be overridden by `x-amz-storage-class` header.
                  If not set - STANDARD is used as a default storage class.
               
               #### Supported values
               
                  Possible values:
               
                  - `STORAGE_CLASS_UNSPECIFIED`
                  - `STANDARD`
                  - `ENHANCED_THROUGHPUT`
                  - `INTELLIGENT`
                  - `FILESYSTEM` - Special storage class only for filesystem buckets.
        :param pulumi.Input[_builtins.bool] force_storage_class: Flag to force usage of default_storage_class, ignoring `x-amz-storage-class` header.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input['StorageV1BucketLifecycleConfigurationArgs'] lifecycle_configuration: :
               
               #### Inner value description
               
                  The lifecycle configuration consists of one or more rules.
                  An Lifecycle configuration can have up to 1,000 rules.
                  Each rule consists of the following:
                  - A filter identifying a subset of objects to which the rule applies.
                    The filter can be based on a key name prefix, object size, or any combination of these.
                  - A status indicating whether the rule is currently active.
                  - One or more lifecycle expiration actions that you want to be performed on the objects
                    identified by the filter. If the state of your bucket is versioning-enabled or versioning-suspended
                    (bucket.spec.versioning_policy equals to ENABLED or SUSPENDED) you can have many versions of the same
                    object (one current version and zero or more noncurrent versions). The system provides predefined actions
                    that you can specify for current and noncurrent object versions.
        :param pulumi.Input[_builtins.float] max_size_bytes: :
               
                  Maximum bucket size.
                  Zero means unlimited.
                  Actual limit can be lower if customer doesn't have enough quota.
                  Real bucket size can go a little higher if customer writes too fast.
        :param pulumi.Input['StorageV1BucketMetadataArgs'] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] object_audit_logging: :
               
                  Object audit logging specifies which requests must be logged - none, all or mutational only.
               
               #### Supported values
               
                  Possible values:
               
                  - `OBJECT_AUDIT_LOGGING_UNSPECIFIED`
                  - `NONE` - Logging is disabled.
                  - `MUTATE_ONLY` - Logging enabled only for mutating requests.
                  - `ALL` - Logging enabled for all requests.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.str] versioning_policy: :
               
                  Supports transitions:
                   * disabled -\\> enabled
                   * disabled -\\> suspended
                   * enabled \\<-\\> suspended
               
               #### Supported values
               
                  Possible values:
               
                  - `VERSIONING_POLICY_UNSPECIFIED`
                  - `DISABLED`
                  - `ENABLED`
                  - `SUSPENDED`
        """
        if bucket_policy is not None:
            pulumi.set(__self__, "bucket_policy", bucket_policy)
        if cors is not None:
            pulumi.set(__self__, "cors", cors)
        if default_storage_class is not None:
            pulumi.set(__self__, "default_storage_class", default_storage_class)
        if force_storage_class is not None:
            pulumi.set(__self__, "force_storage_class", force_storage_class)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if lifecycle_configuration is not None:
            pulumi.set(__self__, "lifecycle_configuration", lifecycle_configuration)
        if max_size_bytes is not None:
            pulumi.set(__self__, "max_size_bytes", max_size_bytes)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if object_audit_logging is not None:
            pulumi.set(__self__, "object_audit_logging", object_audit_logging)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)
        if versioning_policy is not None:
            pulumi.set(__self__, "versioning_policy", versioning_policy)

    @_builtins.property
    @pulumi.getter(name="bucketPolicy")
    def bucket_policy(self) -> pulumi.Input[Optional['StorageV1BucketBucketPolicyArgs']]:
        """
        :

           Bucket policy specifies granular permissions for a bucket.

        #### Inner value description

           Bucket policy specifies granular permissions for a bucket.
        """
        return pulumi.get(self, "bucket_policy")

    @bucket_policy.setter
    def bucket_policy(self, value: pulumi.Input[Optional['StorageV1BucketBucketPolicyArgs']]):
        pulumi.set(self, "bucket_policy", value)

    @_builtins.property
    @pulumi.getter
    def cors(self) -> pulumi.Input[Optional['StorageV1BucketCorsArgs']]:
        """
        :

           Cross-origin resource sharing configuration.

        #### Inner value description

           Cross-origin resource sharing (CORS) configuration.
        """
        return pulumi.get(self, "cors")

    @cors.setter
    def cors(self, value: pulumi.Input[Optional['StorageV1BucketCorsArgs']]):
        pulumi.set(self, "cors", value)

    @_builtins.property
    @pulumi.getter(name="defaultStorageClass")
    def default_storage_class(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Storage class to use by default for uploads to the bucket. It may be overridden by `x-amz-storage-class` header.
           If not set - STANDARD is used as a default storage class.

        #### Supported values

           Possible values:

           - `STORAGE_CLASS_UNSPECIFIED`
           - `STANDARD`
           - `ENHANCED_THROUGHPUT`
           - `INTELLIGENT`
           - `FILESYSTEM` - Special storage class only for filesystem buckets.
        """
        return pulumi.get(self, "default_storage_class")

    @default_storage_class.setter
    def default_storage_class(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "default_storage_class", value)

    @_builtins.property
    @pulumi.getter(name="forceStorageClass")
    def force_storage_class(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Flag to force usage of default_storage_class, ignoring `x-amz-storage-class` header.
        """
        return pulumi.get(self, "force_storage_class")

    @force_storage_class.setter
    def force_storage_class(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "force_storage_class", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleConfiguration")
    def lifecycle_configuration(self) -> pulumi.Input[Optional['StorageV1BucketLifecycleConfigurationArgs']]:
        """
        :

        #### Inner value description

           The lifecycle configuration consists of one or more rules.
           An Lifecycle configuration can have up to 1,000 rules.
           Each rule consists of the following:
           - A filter identifying a subset of objects to which the rule applies.
             The filter can be based on a key name prefix, object size, or any combination of these.
           - A status indicating whether the rule is currently active.
           - One or more lifecycle expiration actions that you want to be performed on the objects
             identified by the filter. If the state of your bucket is versioning-enabled or versioning-suspended
             (bucket.spec.versioning_policy equals to ENABLED or SUSPENDED) you can have many versions of the same
             object (one current version and zero or more noncurrent versions). The system provides predefined actions
             that you can specify for current and noncurrent object versions.
        """
        return pulumi.get(self, "lifecycle_configuration")

    @lifecycle_configuration.setter
    def lifecycle_configuration(self, value: pulumi.Input[Optional['StorageV1BucketLifecycleConfigurationArgs']]):
        pulumi.set(self, "lifecycle_configuration", value)

    @_builtins.property
    @pulumi.getter(name="maxSizeBytes")
    def max_size_bytes(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        :

           Maximum bucket size.
           Zero means unlimited.
           Actual limit can be lower if customer doesn't have enough quota.
           Real bucket size can go a little higher if customer writes too fast.
        """
        return pulumi.get(self, "max_size_bytes")

    @max_size_bytes.setter
    def max_size_bytes(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "max_size_bytes", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['StorageV1BucketMetadataArgs']]:
        """
        :

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['StorageV1BucketMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="objectAuditLogging")
    def object_audit_logging(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Object audit logging specifies which requests must be logged - none, all or mutational only.

        #### Supported values

           Possible values:

           - `OBJECT_AUDIT_LOGGING_UNSPECIFIED`
           - `NONE` - Logging is disabled.
           - `MUTATE_ONLY` - Logging enabled only for mutating requests.
           - `ALL` - Logging enabled for all requests.
        """
        return pulumi.get(self, "object_audit_logging")

    @object_audit_logging.setter
    def object_audit_logging(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "object_audit_logging", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter(name="versioningPolicy")
    def versioning_policy(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Supports transitions:
            * disabled -\\> enabled
            * disabled -\\> suspended
            * enabled \\<-\\> suspended

        #### Supported values

           Possible values:

           - `VERSIONING_POLICY_UNSPECIFIED`
           - `DISABLED`
           - `ENABLED`
           - `SUSPENDED`
        """
        return pulumi.get(self, "versioning_policy")

    @versioning_policy.setter
    def versioning_policy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "versioning_policy", value)


@pulumi.input_type
class _StorageV1BucketState:
    def __init__(__self__, *,
                 bucket_policy: pulumi.Input[Optional['StorageV1BucketBucketPolicyArgs']] = None,
                 cors: pulumi.Input[Optional['StorageV1BucketCorsArgs']] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 default_storage_class: pulumi.Input[Optional[_builtins.str]] = None,
                 force_storage_class: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 labels_all: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 lifecycle_configuration: pulumi.Input[Optional['StorageV1BucketLifecycleConfigurationArgs']] = None,
                 max_size_bytes: pulumi.Input[Optional[_builtins.float]] = None,
                 metadata: pulumi.Input[Optional['StorageV1BucketMetadataArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 object_audit_logging: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_version: pulumi.Input[Optional[_builtins.float]] = None,
                 status: pulumi.Input[Optional['StorageV1BucketStatusArgs']] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None,
                 versioning_policy: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering StorageV1Bucket resources.

        :param pulumi.Input['StorageV1BucketBucketPolicyArgs'] bucket_policy: :
               
                  Bucket policy specifies granular permissions for a bucket.
               
               #### Inner value description
               
                  Bucket policy specifies granular permissions for a bucket.
        :param pulumi.Input['StorageV1BucketCorsArgs'] cors: :
               
                  Cross-origin resource sharing configuration.
               
               #### Inner value description
               
                  Cross-origin resource sharing (CORS) configuration.
        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[_builtins.str] default_storage_class: :
               
                  Storage class to use by default for uploads to the bucket. It may be overridden by `x-amz-storage-class` header.
                  If not set - STANDARD is used as a default storage class.
               
               #### Supported values
               
                  Possible values:
               
                  - `STORAGE_CLASS_UNSPECIFIED`
                  - `STANDARD`
                  - `ENHANCED_THROUGHPUT`
                  - `INTELLIGENT`
                  - `FILESYSTEM` - Special storage class only for filesystem buckets.
        :param pulumi.Input[_builtins.bool] force_storage_class: Flag to force usage of default_storage_class, ignoring `x-amz-storage-class` header.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels_all: Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        :param pulumi.Input['StorageV1BucketLifecycleConfigurationArgs'] lifecycle_configuration: :
               
               #### Inner value description
               
                  The lifecycle configuration consists of one or more rules.
                  An Lifecycle configuration can have up to 1,000 rules.
                  Each rule consists of the following:
                  - A filter identifying a subset of objects to which the rule applies.
                    The filter can be based on a key name prefix, object size, or any combination of these.
                  - A status indicating whether the rule is currently active.
                  - One or more lifecycle expiration actions that you want to be performed on the objects
                    identified by the filter. If the state of your bucket is versioning-enabled or versioning-suspended
                    (bucket.spec.versioning_policy equals to ENABLED or SUSPENDED) you can have many versions of the same
                    object (one current version and zero or more noncurrent versions). The system provides predefined actions
                    that you can specify for current and noncurrent object versions.
        :param pulumi.Input[_builtins.float] max_size_bytes: :
               
                  Maximum bucket size.
                  Zero means unlimited.
                  Actual limit can be lower if customer doesn't have enough quota.
                  Real bucket size can go a little higher if customer writes too fast.
        :param pulumi.Input['StorageV1BucketMetadataArgs'] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] object_audit_logging: :
               
                  Object audit logging specifies which requests must be logged - none, all or mutational only.
               
               #### Supported values
               
                  Possible values:
               
                  - `OBJECT_AUDIT_LOGGING_UNSPECIFIED`
                  - `NONE` - Logging is disabled.
                  - `MUTATE_ONLY` - Logging enabled only for mutating requests.
                  - `ALL` - Logging enabled for all requests.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[_builtins.str] versioning_policy: :
               
                  Supports transitions:
                   * disabled -\\> enabled
                   * disabled -\\> suspended
                   * enabled \\<-\\> suspended
               
               #### Supported values
               
                  Possible values:
               
                  - `VERSIONING_POLICY_UNSPECIFIED`
                  - `DISABLED`
                  - `ENABLED`
                  - `SUSPENDED`
        """
        if bucket_policy is not None:
            pulumi.set(__self__, "bucket_policy", bucket_policy)
        if cors is not None:
            pulumi.set(__self__, "cors", cors)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if default_storage_class is not None:
            pulumi.set(__self__, "default_storage_class", default_storage_class)
        if force_storage_class is not None:
            pulumi.set(__self__, "force_storage_class", force_storage_class)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if labels_all is not None:
            pulumi.set(__self__, "labels_all", labels_all)
        if lifecycle_configuration is not None:
            pulumi.set(__self__, "lifecycle_configuration", lifecycle_configuration)
        if max_size_bytes is not None:
            pulumi.set(__self__, "max_size_bytes", max_size_bytes)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if object_audit_logging is not None:
            pulumi.set(__self__, "object_audit_logging", object_audit_logging)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)
        if resource_version is not None:
            pulumi.set(__self__, "resource_version", resource_version)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)
        if versioning_policy is not None:
            pulumi.set(__self__, "versioning_policy", versioning_policy)

    @_builtins.property
    @pulumi.getter(name="bucketPolicy")
    def bucket_policy(self) -> pulumi.Input[Optional['StorageV1BucketBucketPolicyArgs']]:
        """
        :

           Bucket policy specifies granular permissions for a bucket.

        #### Inner value description

           Bucket policy specifies granular permissions for a bucket.
        """
        return pulumi.get(self, "bucket_policy")

    @bucket_policy.setter
    def bucket_policy(self, value: pulumi.Input[Optional['StorageV1BucketBucketPolicyArgs']]):
        pulumi.set(self, "bucket_policy", value)

    @_builtins.property
    @pulumi.getter
    def cors(self) -> pulumi.Input[Optional['StorageV1BucketCorsArgs']]:
        """
        :

           Cross-origin resource sharing configuration.

        #### Inner value description

           Cross-origin resource sharing (CORS) configuration.
        """
        return pulumi.get(self, "cors")

    @cors.setter
    def cors(self, value: pulumi.Input[Optional['StorageV1BucketCorsArgs']]):
        pulumi.set(self, "cors", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was created.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="defaultStorageClass")
    def default_storage_class(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Storage class to use by default for uploads to the bucket. It may be overridden by `x-amz-storage-class` header.
           If not set - STANDARD is used as a default storage class.

        #### Supported values

           Possible values:

           - `STORAGE_CLASS_UNSPECIFIED`
           - `STANDARD`
           - `ENHANCED_THROUGHPUT`
           - `INTELLIGENT`
           - `FILESYSTEM` - Special storage class only for filesystem buckets.
        """
        return pulumi.get(self, "default_storage_class")

    @default_storage_class.setter
    def default_storage_class(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "default_storage_class", value)

    @_builtins.property
    @pulumi.getter(name="forceStorageClass")
    def force_storage_class(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Flag to force usage of default_storage_class, ignoring `x-amz-storage-class` header.
        """
        return pulumi.get(self, "force_storage_class")

    @force_storage_class.setter
    def force_storage_class(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "force_storage_class", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="labelsAll")
    def labels_all(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        """
        return pulumi.get(self, "labels_all")

    @labels_all.setter
    def labels_all(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels_all", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleConfiguration")
    def lifecycle_configuration(self) -> pulumi.Input[Optional['StorageV1BucketLifecycleConfigurationArgs']]:
        """
        :

        #### Inner value description

           The lifecycle configuration consists of one or more rules.
           An Lifecycle configuration can have up to 1,000 rules.
           Each rule consists of the following:
           - A filter identifying a subset of objects to which the rule applies.
             The filter can be based on a key name prefix, object size, or any combination of these.
           - A status indicating whether the rule is currently active.
           - One or more lifecycle expiration actions that you want to be performed on the objects
             identified by the filter. If the state of your bucket is versioning-enabled or versioning-suspended
             (bucket.spec.versioning_policy equals to ENABLED or SUSPENDED) you can have many versions of the same
             object (one current version and zero or more noncurrent versions). The system provides predefined actions
             that you can specify for current and noncurrent object versions.
        """
        return pulumi.get(self, "lifecycle_configuration")

    @lifecycle_configuration.setter
    def lifecycle_configuration(self, value: pulumi.Input[Optional['StorageV1BucketLifecycleConfigurationArgs']]):
        pulumi.set(self, "lifecycle_configuration", value)

    @_builtins.property
    @pulumi.getter(name="maxSizeBytes")
    def max_size_bytes(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        :

           Maximum bucket size.
           Zero means unlimited.
           Actual limit can be lower if customer doesn't have enough quota.
           Real bucket size can go a little higher if customer writes too fast.
        """
        return pulumi.get(self, "max_size_bytes")

    @max_size_bytes.setter
    def max_size_bytes(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "max_size_bytes", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['StorageV1BucketMetadataArgs']]:
        """
        :

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['StorageV1BucketMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="objectAuditLogging")
    def object_audit_logging(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Object audit logging specifies which requests must be logged - none, all or mutational only.

        #### Supported values

           Possible values:

           - `OBJECT_AUDIT_LOGGING_UNSPECIFIED`
           - `NONE` - Logging is disabled.
           - `MUTATE_ONLY` - Logging enabled only for mutating requests.
           - `ALL` - Logging enabled for all requests.
        """
        return pulumi.get(self, "object_audit_logging")

    @object_audit_logging.setter
    def object_audit_logging(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "object_audit_logging", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @resource_version.setter
    def resource_version(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "resource_version", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional['StorageV1BucketStatusArgs']]:
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional['StorageV1BucketStatusArgs']]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was last updated.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)

    @_builtins.property
    @pulumi.getter(name="versioningPolicy")
    def versioning_policy(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Supports transitions:
            * disabled -\\> enabled
            * disabled -\\> suspended
            * enabled \\<-\\> suspended

        #### Supported values

           Possible values:

           - `VERSIONING_POLICY_UNSPECIFIED`
           - `DISABLED`
           - `ENABLED`
           - `SUSPENDED`
        """
        return pulumi.get(self, "versioning_policy")

    @versioning_policy.setter
    def versioning_policy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "versioning_policy", value)


@pulumi.type_token("nebius:index/storageV1Bucket:StorageV1Bucket")
class StorageV1Bucket(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_policy: pulumi.Input[Optional[Union['StorageV1BucketBucketPolicyArgs', 'StorageV1BucketBucketPolicyArgsDict']]] = None,
                 cors: pulumi.Input[Optional[Union['StorageV1BucketCorsArgs', 'StorageV1BucketCorsArgsDict']]] = None,
                 default_storage_class: pulumi.Input[Optional[_builtins.str]] = None,
                 force_storage_class: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 lifecycle_configuration: pulumi.Input[Optional[Union['StorageV1BucketLifecycleConfigurationArgs', 'StorageV1BucketLifecycleConfigurationArgsDict']]] = None,
                 max_size_bytes: pulumi.Input[Optional[_builtins.float]] = None,
                 metadata: pulumi.Input[Optional[Union['StorageV1BucketMetadataArgs', 'StorageV1BucketMetadataArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 object_audit_logging: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 versioning_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a StorageV1Bucket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['StorageV1BucketBucketPolicyArgs', 'StorageV1BucketBucketPolicyArgsDict']] bucket_policy: :
               
                  Bucket policy specifies granular permissions for a bucket.
               
               #### Inner value description
               
                  Bucket policy specifies granular permissions for a bucket.
        :param pulumi.Input[Union['StorageV1BucketCorsArgs', 'StorageV1BucketCorsArgsDict']] cors: :
               
                  Cross-origin resource sharing configuration.
               
               #### Inner value description
               
                  Cross-origin resource sharing (CORS) configuration.
        :param pulumi.Input[_builtins.str] default_storage_class: :
               
                  Storage class to use by default for uploads to the bucket. It may be overridden by `x-amz-storage-class` header.
                  If not set - STANDARD is used as a default storage class.
               
               #### Supported values
               
                  Possible values:
               
                  - `STORAGE_CLASS_UNSPECIFIED`
                  - `STANDARD`
                  - `ENHANCED_THROUGHPUT`
                  - `INTELLIGENT`
                  - `FILESYSTEM` - Special storage class only for filesystem buckets.
        :param pulumi.Input[_builtins.bool] force_storage_class: Flag to force usage of default_storage_class, ignoring `x-amz-storage-class` header.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Union['StorageV1BucketLifecycleConfigurationArgs', 'StorageV1BucketLifecycleConfigurationArgsDict']] lifecycle_configuration: :
               
               #### Inner value description
               
                  The lifecycle configuration consists of one or more rules.
                  An Lifecycle configuration can have up to 1,000 rules.
                  Each rule consists of the following:
                  - A filter identifying a subset of objects to which the rule applies.
                    The filter can be based on a key name prefix, object size, or any combination of these.
                  - A status indicating whether the rule is currently active.
                  - One or more lifecycle expiration actions that you want to be performed on the objects
                    identified by the filter. If the state of your bucket is versioning-enabled or versioning-suspended
                    (bucket.spec.versioning_policy equals to ENABLED or SUSPENDED) you can have many versions of the same
                    object (one current version and zero or more noncurrent versions). The system provides predefined actions
                    that you can specify for current and noncurrent object versions.
        :param pulumi.Input[_builtins.float] max_size_bytes: :
               
                  Maximum bucket size.
                  Zero means unlimited.
                  Actual limit can be lower if customer doesn't have enough quota.
                  Real bucket size can go a little higher if customer writes too fast.
        :param pulumi.Input[Union['StorageV1BucketMetadataArgs', 'StorageV1BucketMetadataArgsDict']] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] object_audit_logging: :
               
                  Object audit logging specifies which requests must be logged - none, all or mutational only.
               
               #### Supported values
               
                  Possible values:
               
                  - `OBJECT_AUDIT_LOGGING_UNSPECIFIED`
                  - `NONE` - Logging is disabled.
                  - `MUTATE_ONLY` - Logging enabled only for mutating requests.
                  - `ALL` - Logging enabled for all requests.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.str] versioning_policy: :
               
                  Supports transitions:
                   * disabled -\\> enabled
                   * disabled -\\> suspended
                   * enabled \\<-\\> suspended
               
               #### Supported values
               
                  Possible values:
               
                  - `VERSIONING_POLICY_UNSPECIFIED`
                  - `DISABLED`
                  - `ENABLED`
                  - `SUSPENDED`
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[StorageV1BucketArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a StorageV1Bucket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param StorageV1BucketArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(StorageV1BucketArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_policy: pulumi.Input[Optional[Union['StorageV1BucketBucketPolicyArgs', 'StorageV1BucketBucketPolicyArgsDict']]] = None,
                 cors: pulumi.Input[Optional[Union['StorageV1BucketCorsArgs', 'StorageV1BucketCorsArgsDict']]] = None,
                 default_storage_class: pulumi.Input[Optional[_builtins.str]] = None,
                 force_storage_class: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 lifecycle_configuration: pulumi.Input[Optional[Union['StorageV1BucketLifecycleConfigurationArgs', 'StorageV1BucketLifecycleConfigurationArgsDict']]] = None,
                 max_size_bytes: pulumi.Input[Optional[_builtins.float]] = None,
                 metadata: pulumi.Input[Optional[Union['StorageV1BucketMetadataArgs', 'StorageV1BucketMetadataArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 object_audit_logging: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 versioning_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = StorageV1BucketArgs.__new__(StorageV1BucketArgs)

            __props__.__dict__["bucket_policy"] = bucket_policy
            __props__.__dict__["cors"] = cors
            __props__.__dict__["default_storage_class"] = default_storage_class
            __props__.__dict__["force_storage_class"] = force_storage_class
            __props__.__dict__["labels"] = labels
            __props__.__dict__["lifecycle_configuration"] = lifecycle_configuration
            __props__.__dict__["max_size_bytes"] = max_size_bytes
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["name"] = name
            __props__.__dict__["object_audit_logging"] = object_audit_logging
            __props__.__dict__["parent_id"] = parent_id
            __props__.__dict__["versioning_policy"] = versioning_policy
            __props__.__dict__["created_at"] = None
            __props__.__dict__["labels_all"] = None
            __props__.__dict__["resource_version"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["updated_at"] = None
        super(StorageV1Bucket, __self__).__init__(
            'nebius:index/storageV1Bucket:StorageV1Bucket',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            bucket_policy: pulumi.Input[Optional[Union['StorageV1BucketBucketPolicyArgs', 'StorageV1BucketBucketPolicyArgsDict']]] = None,
            cors: pulumi.Input[Optional[Union['StorageV1BucketCorsArgs', 'StorageV1BucketCorsArgsDict']]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            default_storage_class: pulumi.Input[Optional[_builtins.str]] = None,
            force_storage_class: pulumi.Input[Optional[_builtins.bool]] = None,
            labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            labels_all: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            lifecycle_configuration: pulumi.Input[Optional[Union['StorageV1BucketLifecycleConfigurationArgs', 'StorageV1BucketLifecycleConfigurationArgsDict']]] = None,
            max_size_bytes: pulumi.Input[Optional[_builtins.float]] = None,
            metadata: pulumi.Input[Optional[Union['StorageV1BucketMetadataArgs', 'StorageV1BucketMetadataArgsDict']]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            object_audit_logging: pulumi.Input[Optional[_builtins.str]] = None,
            parent_id: pulumi.Input[Optional[_builtins.str]] = None,
            resource_version: pulumi.Input[Optional[_builtins.float]] = None,
            status: pulumi.Input[Optional[Union['StorageV1BucketStatusArgs', 'StorageV1BucketStatusArgsDict']]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None,
            versioning_policy: pulumi.Input[Optional[_builtins.str]] = None) -> 'StorageV1Bucket':
        """
        Get an existing StorageV1Bucket resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['StorageV1BucketBucketPolicyArgs', 'StorageV1BucketBucketPolicyArgsDict']] bucket_policy: :
               
                  Bucket policy specifies granular permissions for a bucket.
               
               #### Inner value description
               
                  Bucket policy specifies granular permissions for a bucket.
        :param pulumi.Input[Union['StorageV1BucketCorsArgs', 'StorageV1BucketCorsArgsDict']] cors: :
               
                  Cross-origin resource sharing configuration.
               
               #### Inner value description
               
                  Cross-origin resource sharing (CORS) configuration.
        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[_builtins.str] default_storage_class: :
               
                  Storage class to use by default for uploads to the bucket. It may be overridden by `x-amz-storage-class` header.
                  If not set - STANDARD is used as a default storage class.
               
               #### Supported values
               
                  Possible values:
               
                  - `STORAGE_CLASS_UNSPECIFIED`
                  - `STANDARD`
                  - `ENHANCED_THROUGHPUT`
                  - `INTELLIGENT`
                  - `FILESYSTEM` - Special storage class only for filesystem buckets.
        :param pulumi.Input[_builtins.bool] force_storage_class: Flag to force usage of default_storage_class, ignoring `x-amz-storage-class` header.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels_all: Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        :param pulumi.Input[Union['StorageV1BucketLifecycleConfigurationArgs', 'StorageV1BucketLifecycleConfigurationArgsDict']] lifecycle_configuration: :
               
               #### Inner value description
               
                  The lifecycle configuration consists of one or more rules.
                  An Lifecycle configuration can have up to 1,000 rules.
                  Each rule consists of the following:
                  - A filter identifying a subset of objects to which the rule applies.
                    The filter can be based on a key name prefix, object size, or any combination of these.
                  - A status indicating whether the rule is currently active.
                  - One or more lifecycle expiration actions that you want to be performed on the objects
                    identified by the filter. If the state of your bucket is versioning-enabled or versioning-suspended
                    (bucket.spec.versioning_policy equals to ENABLED or SUSPENDED) you can have many versions of the same
                    object (one current version and zero or more noncurrent versions). The system provides predefined actions
                    that you can specify for current and noncurrent object versions.
        :param pulumi.Input[_builtins.float] max_size_bytes: :
               
                  Maximum bucket size.
                  Zero means unlimited.
                  Actual limit can be lower if customer doesn't have enough quota.
                  Real bucket size can go a little higher if customer writes too fast.
        :param pulumi.Input[Union['StorageV1BucketMetadataArgs', 'StorageV1BucketMetadataArgsDict']] metadata: :
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] object_audit_logging: :
               
                  Object audit logging specifies which requests must be logged - none, all or mutational only.
               
               #### Supported values
               
                  Possible values:
               
                  - `OBJECT_AUDIT_LOGGING_UNSPECIFIED`
                  - `NONE` - Logging is disabled.
                  - `MUTATE_ONLY` - Logging enabled only for mutating requests.
                  - `ALL` - Logging enabled for all requests.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[_builtins.str] versioning_policy: :
               
                  Supports transitions:
                   * disabled -\\> enabled
                   * disabled -\\> suspended
                   * enabled \\<-\\> suspended
               
               #### Supported values
               
                  Possible values:
               
                  - `VERSIONING_POLICY_UNSPECIFIED`
                  - `DISABLED`
                  - `ENABLED`
                  - `SUSPENDED`
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _StorageV1BucketState.__new__(_StorageV1BucketState)

        __props__.__dict__["bucket_policy"] = bucket_policy
        __props__.__dict__["cors"] = cors
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["default_storage_class"] = default_storage_class
        __props__.__dict__["force_storage_class"] = force_storage_class
        __props__.__dict__["labels"] = labels
        __props__.__dict__["labels_all"] = labels_all
        __props__.__dict__["lifecycle_configuration"] = lifecycle_configuration
        __props__.__dict__["max_size_bytes"] = max_size_bytes
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["name"] = name
        __props__.__dict__["object_audit_logging"] = object_audit_logging
        __props__.__dict__["parent_id"] = parent_id
        __props__.__dict__["resource_version"] = resource_version
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        __props__.__dict__["versioning_policy"] = versioning_policy
        return StorageV1Bucket(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="bucketPolicy")
    def bucket_policy(self) -> pulumi.Output[Optional['outputs.StorageV1BucketBucketPolicy']]:
        """
        :

           Bucket policy specifies granular permissions for a bucket.

        #### Inner value description

           Bucket policy specifies granular permissions for a bucket.
        """
        return pulumi.get(self, "bucket_policy")

    @_builtins.property
    @pulumi.getter
    def cors(self) -> pulumi.Output[Optional['outputs.StorageV1BucketCors']]:
        """
        :

           Cross-origin resource sharing configuration.

        #### Inner value description

           Cross-origin resource sharing (CORS) configuration.
        """
        return pulumi.get(self, "cors")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was created.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="defaultStorageClass")
    def default_storage_class(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        :

           Storage class to use by default for uploads to the bucket. It may be overridden by `x-amz-storage-class` header.
           If not set - STANDARD is used as a default storage class.

        #### Supported values

           Possible values:

           - `STORAGE_CLASS_UNSPECIFIED`
           - `STANDARD`
           - `ENHANCED_THROUGHPUT`
           - `INTELLIGENT`
           - `FILESYSTEM` - Special storage class only for filesystem buckets.
        """
        return pulumi.get(self, "default_storage_class")

    @_builtins.property
    @pulumi.getter(name="forceStorageClass")
    def force_storage_class(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Flag to force usage of default_storage_class, ignoring `x-amz-storage-class` header.
        """
        return pulumi.get(self, "force_storage_class")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="labelsAll")
    def labels_all(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        """
        return pulumi.get(self, "labels_all")

    @_builtins.property
    @pulumi.getter(name="lifecycleConfiguration")
    def lifecycle_configuration(self) -> pulumi.Output['outputs.StorageV1BucketLifecycleConfiguration']:
        """
        :

        #### Inner value description

           The lifecycle configuration consists of one or more rules.
           An Lifecycle configuration can have up to 1,000 rules.
           Each rule consists of the following:
           - A filter identifying a subset of objects to which the rule applies.
             The filter can be based on a key name prefix, object size, or any combination of these.
           - A status indicating whether the rule is currently active.
           - One or more lifecycle expiration actions that you want to be performed on the objects
             identified by the filter. If the state of your bucket is versioning-enabled or versioning-suspended
             (bucket.spec.versioning_policy equals to ENABLED or SUSPENDED) you can have many versions of the same
             object (one current version and zero or more noncurrent versions). The system provides predefined actions
             that you can specify for current and noncurrent object versions.
        """
        return pulumi.get(self, "lifecycle_configuration")

    @_builtins.property
    @pulumi.getter(name="maxSizeBytes")
    def max_size_bytes(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        :

           Maximum bucket size.
           Zero means unlimited.
           Actual limit can be lower if customer doesn't have enough quota.
           Real bucket size can go a little higher if customer writes too fast.
        """
        return pulumi.get(self, "max_size_bytes")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['outputs.StorageV1BucketMetadata']:
        """
        :

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="objectAuditLogging")
    def object_audit_logging(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        :

           Object audit logging specifies which requests must be logged - none, all or mutational only.

        #### Supported values

           Possible values:

           - `OBJECT_AUDIT_LOGGING_UNSPECIFIED`
           - `NONE` - Logging is disabled.
           - `MUTATE_ONLY` - Logging enabled only for mutating requests.
           - `ALL` - Logging enabled for all requests.
        """
        return pulumi.get(self, "object_audit_logging")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> pulumi.Output[_builtins.float]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output['outputs.StorageV1BucketStatus']:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was last updated.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="versioningPolicy")
    def versioning_policy(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Supports transitions:
            * disabled -\\> enabled
            * disabled -\\> suspended
            * enabled \\<-\\> suspended

        #### Supported values

           Possible values:

           - `VERSIONING_POLICY_UNSPECIFIED`
           - `DISABLED`
           - `ENABLED`
           - `SUSPENDED`
        """
        return pulumi.get(self, "versioning_policy")

