# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['VpcV1NetworkArgs', 'VpcV1Network']

@pulumi.input_type
class VpcV1NetworkArgs:
    def __init__(__self__, *,
                 ipv4_private_pools: pulumi.Input[Optional['VpcV1NetworkIpv4PrivatePoolsArgs']] = None,
                 ipv4_public_pools: pulumi.Input[Optional['VpcV1NetworkIpv4PublicPoolsArgs']] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional['VpcV1NetworkMetadataArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a VpcV1Network resource.

        :param pulumi.Input['VpcV1NetworkIpv4PrivatePoolsArgs'] ipv4_private_pools: :
               
                  Pools for private IPv4 addresses.
                  Default private pools will be created if not specified.
                  Default private pools are referred here
                  https://docs.nebius.com/vpc/addressing/available-addresses
        :param pulumi.Input['VpcV1NetworkIpv4PublicPoolsArgs'] ipv4_public_pools: :
               
                  Pools for public IPv4 addresses.
                  Default public pool will be used if not specified.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input['VpcV1NetworkMetadataArgs'] metadata: :
               
                  Metadata for the network resource.
                  `metadata.parent_id` represents IAM container
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        """
        if ipv4_private_pools is not None:
            pulumi.set(__self__, "ipv4_private_pools", ipv4_private_pools)
        if ipv4_public_pools is not None:
            pulumi.set(__self__, "ipv4_public_pools", ipv4_public_pools)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)

    @_builtins.property
    @pulumi.getter(name="ipv4PrivatePools")
    def ipv4_private_pools(self) -> pulumi.Input[Optional['VpcV1NetworkIpv4PrivatePoolsArgs']]:
        """
        :

           Pools for private IPv4 addresses.
           Default private pools will be created if not specified.
           Default private pools are referred here
           https://docs.nebius.com/vpc/addressing/available-addresses
        """
        return pulumi.get(self, "ipv4_private_pools")

    @ipv4_private_pools.setter
    def ipv4_private_pools(self, value: pulumi.Input[Optional['VpcV1NetworkIpv4PrivatePoolsArgs']]):
        pulumi.set(self, "ipv4_private_pools", value)

    @_builtins.property
    @pulumi.getter(name="ipv4PublicPools")
    def ipv4_public_pools(self) -> pulumi.Input[Optional['VpcV1NetworkIpv4PublicPoolsArgs']]:
        """
        :

           Pools for public IPv4 addresses.
           Default public pool will be used if not specified.
        """
        return pulumi.get(self, "ipv4_public_pools")

    @ipv4_public_pools.setter
    def ipv4_public_pools(self, value: pulumi.Input[Optional['VpcV1NetworkIpv4PublicPoolsArgs']]):
        pulumi.set(self, "ipv4_public_pools", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['VpcV1NetworkMetadataArgs']]:
        """
        :

           Metadata for the network resource.
           `metadata.parent_id` represents IAM container

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['VpcV1NetworkMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent_id", value)


@pulumi.input_type
class _VpcV1NetworkState:
    def __init__(__self__, *,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 ipv4_private_pools: pulumi.Input[Optional['VpcV1NetworkIpv4PrivatePoolsArgs']] = None,
                 ipv4_public_pools: pulumi.Input[Optional['VpcV1NetworkIpv4PublicPoolsArgs']] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 labels_all: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional['VpcV1NetworkMetadataArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_version: pulumi.Input[Optional[_builtins.float]] = None,
                 status: pulumi.Input[Optional['VpcV1NetworkStatusArgs']] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering VpcV1Network resources.

        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input['VpcV1NetworkIpv4PrivatePoolsArgs'] ipv4_private_pools: :
               
                  Pools for private IPv4 addresses.
                  Default private pools will be created if not specified.
                  Default private pools are referred here
                  https://docs.nebius.com/vpc/addressing/available-addresses
        :param pulumi.Input['VpcV1NetworkIpv4PublicPoolsArgs'] ipv4_public_pools: :
               
                  Pools for public IPv4 addresses.
                  Default public pool will be used if not specified.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels_all: Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        :param pulumi.Input['VpcV1NetworkMetadataArgs'] metadata: :
               
                  Metadata for the network resource.
                  `metadata.parent_id` represents IAM container
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input['VpcV1NetworkStatusArgs'] status: Status of the network.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if ipv4_private_pools is not None:
            pulumi.set(__self__, "ipv4_private_pools", ipv4_private_pools)
        if ipv4_public_pools is not None:
            pulumi.set(__self__, "ipv4_public_pools", ipv4_public_pools)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if labels_all is not None:
            pulumi.set(__self__, "labels_all", labels_all)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)
        if resource_version is not None:
            pulumi.set(__self__, "resource_version", resource_version)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was created.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="ipv4PrivatePools")
    def ipv4_private_pools(self) -> pulumi.Input[Optional['VpcV1NetworkIpv4PrivatePoolsArgs']]:
        """
        :

           Pools for private IPv4 addresses.
           Default private pools will be created if not specified.
           Default private pools are referred here
           https://docs.nebius.com/vpc/addressing/available-addresses
        """
        return pulumi.get(self, "ipv4_private_pools")

    @ipv4_private_pools.setter
    def ipv4_private_pools(self, value: pulumi.Input[Optional['VpcV1NetworkIpv4PrivatePoolsArgs']]):
        pulumi.set(self, "ipv4_private_pools", value)

    @_builtins.property
    @pulumi.getter(name="ipv4PublicPools")
    def ipv4_public_pools(self) -> pulumi.Input[Optional['VpcV1NetworkIpv4PublicPoolsArgs']]:
        """
        :

           Pools for public IPv4 addresses.
           Default public pool will be used if not specified.
        """
        return pulumi.get(self, "ipv4_public_pools")

    @ipv4_public_pools.setter
    def ipv4_public_pools(self, value: pulumi.Input[Optional['VpcV1NetworkIpv4PublicPoolsArgs']]):
        pulumi.set(self, "ipv4_public_pools", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="labelsAll")
    def labels_all(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        """
        return pulumi.get(self, "labels_all")

    @labels_all.setter
    def labels_all(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels_all", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['VpcV1NetworkMetadataArgs']]:
        """
        :

           Metadata for the network resource.
           `metadata.parent_id` represents IAM container

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['VpcV1NetworkMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @parent_id.setter
    def parent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent_id", value)

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @resource_version.setter
    def resource_version(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "resource_version", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional['VpcV1NetworkStatusArgs']]:
        """
        Status of the network.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional['VpcV1NetworkStatusArgs']]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        :

           Timestamp indicating when the resource was last updated.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("nebius:index/vpcV1Network:VpcV1Network")
class VpcV1Network(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ipv4_private_pools: pulumi.Input[Optional[Union['VpcV1NetworkIpv4PrivatePoolsArgs', 'VpcV1NetworkIpv4PrivatePoolsArgsDict']]] = None,
                 ipv4_public_pools: pulumi.Input[Optional[Union['VpcV1NetworkIpv4PublicPoolsArgs', 'VpcV1NetworkIpv4PublicPoolsArgsDict']]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional[Union['VpcV1NetworkMetadataArgs', 'VpcV1NetworkMetadataArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a VpcV1Network resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['VpcV1NetworkIpv4PrivatePoolsArgs', 'VpcV1NetworkIpv4PrivatePoolsArgsDict']] ipv4_private_pools: :
               
                  Pools for private IPv4 addresses.
                  Default private pools will be created if not specified.
                  Default private pools are referred here
                  https://docs.nebius.com/vpc/addressing/available-addresses
        :param pulumi.Input[Union['VpcV1NetworkIpv4PublicPoolsArgs', 'VpcV1NetworkIpv4PublicPoolsArgsDict']] ipv4_public_pools: :
               
                  Pools for public IPv4 addresses.
                  Default public pool will be used if not specified.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Union['VpcV1NetworkMetadataArgs', 'VpcV1NetworkMetadataArgsDict']] metadata: :
               
                  Metadata for the network resource.
                  `metadata.parent_id` represents IAM container
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[VpcV1NetworkArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a VpcV1Network resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param VpcV1NetworkArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VpcV1NetworkArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ipv4_private_pools: pulumi.Input[Optional[Union['VpcV1NetworkIpv4PrivatePoolsArgs', 'VpcV1NetworkIpv4PrivatePoolsArgsDict']]] = None,
                 ipv4_public_pools: pulumi.Input[Optional[Union['VpcV1NetworkIpv4PublicPoolsArgs', 'VpcV1NetworkIpv4PublicPoolsArgsDict']]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional[Union['VpcV1NetworkMetadataArgs', 'VpcV1NetworkMetadataArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VpcV1NetworkArgs.__new__(VpcV1NetworkArgs)

            __props__.__dict__["ipv4_private_pools"] = ipv4_private_pools
            __props__.__dict__["ipv4_public_pools"] = ipv4_public_pools
            __props__.__dict__["labels"] = labels
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["name"] = name
            __props__.__dict__["parent_id"] = parent_id
            __props__.__dict__["created_at"] = None
            __props__.__dict__["labels_all"] = None
            __props__.__dict__["resource_version"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["updated_at"] = None
        super(VpcV1Network, __self__).__init__(
            'nebius:index/vpcV1Network:VpcV1Network',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            ipv4_private_pools: pulumi.Input[Optional[Union['VpcV1NetworkIpv4PrivatePoolsArgs', 'VpcV1NetworkIpv4PrivatePoolsArgsDict']]] = None,
            ipv4_public_pools: pulumi.Input[Optional[Union['VpcV1NetworkIpv4PublicPoolsArgs', 'VpcV1NetworkIpv4PublicPoolsArgsDict']]] = None,
            labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            labels_all: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            metadata: pulumi.Input[Optional[Union['VpcV1NetworkMetadataArgs', 'VpcV1NetworkMetadataArgsDict']]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            parent_id: pulumi.Input[Optional[_builtins.str]] = None,
            resource_version: pulumi.Input[Optional[_builtins.float]] = None,
            status: pulumi.Input[Optional[Union['VpcV1NetworkStatusArgs', 'VpcV1NetworkStatusArgsDict']]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None) -> 'VpcV1Network':
        """
        Get an existing VpcV1Network resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_at: :
               
                  Timestamp indicating when the resource was created.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        :param pulumi.Input[Union['VpcV1NetworkIpv4PrivatePoolsArgs', 'VpcV1NetworkIpv4PrivatePoolsArgsDict']] ipv4_private_pools: :
               
                  Pools for private IPv4 addresses.
                  Default private pools will be created if not specified.
                  Default private pools are referred here
                  https://docs.nebius.com/vpc/addressing/available-addresses
        :param pulumi.Input[Union['VpcV1NetworkIpv4PublicPoolsArgs', 'VpcV1NetworkIpv4PublicPoolsArgsDict']] ipv4_public_pools: :
               
                  Pools for public IPv4 addresses.
                  Default public pool will be used if not specified.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels associated with the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels_all: Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        :param pulumi.Input[Union['VpcV1NetworkMetadataArgs', 'VpcV1NetworkMetadataArgsDict']] metadata: :
               
                  Metadata for the network resource.
                  `metadata.parent_id` represents IAM container
               
               #### Inner value description
               
                  Common resource metadata.
        :param pulumi.Input[_builtins.str] name: Human readable name for the resource.
        :param pulumi.Input[_builtins.str] parent_id: Identifier of the parent resource to which the resource belongs.
        :param pulumi.Input[_builtins.float] resource_version: :
               
                  Version of the resource for safe concurrent modifications and consistent reads.
                  Positive and monotonically increases on each resource spec change (but *not* on each change of the
                  resource's container(s) or status).
                  Service allows zero value or current.
        :param pulumi.Input[Union['VpcV1NetworkStatusArgs', 'VpcV1NetworkStatusArgsDict']] status: Status of the network.
        :param pulumi.Input[_builtins.str] updated_at: :
               
                  Timestamp indicating when the resource was last updated.
               
                  A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _VpcV1NetworkState.__new__(_VpcV1NetworkState)

        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["ipv4_private_pools"] = ipv4_private_pools
        __props__.__dict__["ipv4_public_pools"] = ipv4_public_pools
        __props__.__dict__["labels"] = labels
        __props__.__dict__["labels_all"] = labels_all
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["name"] = name
        __props__.__dict__["parent_id"] = parent_id
        __props__.__dict__["resource_version"] = resource_version
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        return VpcV1Network(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was created.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="ipv4PrivatePools")
    def ipv4_private_pools(self) -> pulumi.Output['outputs.VpcV1NetworkIpv4PrivatePools']:
        """
        :

           Pools for private IPv4 addresses.
           Default private pools will be created if not specified.
           Default private pools are referred here
           https://docs.nebius.com/vpc/addressing/available-addresses
        """
        return pulumi.get(self, "ipv4_private_pools")

    @_builtins.property
    @pulumi.getter(name="ipv4PublicPools")
    def ipv4_public_pools(self) -> pulumi.Output['outputs.VpcV1NetworkIpv4PublicPools']:
        """
        :

           Pools for public IPv4 addresses.
           Default public pool will be used if not specified.
        """
        return pulumi.get(self, "ipv4_public_pools")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Labels associated with the resource.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="labelsAll")
    def labels_all(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Effective labels sent to the API after merging provider <span pulumi-lang-nodejs="`defaultLabels`" pulumi-lang-dotnet="`DefaultLabels`" pulumi-lang-go="`defaultLabels`" pulumi-lang-python="`default_labels`" pulumi-lang-yaml="`defaultLabels`" pulumi-lang-java="`defaultLabels`" pulumi-lang-hcl="`default_labels`">`defaultLabels`</span> with resource <span pulumi-lang-nodejs="`labels`" pulumi-lang-dotnet="`Labels`" pulumi-lang-go="`labels`" pulumi-lang-python="`labels`" pulumi-lang-yaml="`labels`" pulumi-lang-java="`labels`" pulumi-lang-hcl="`labels`">`labels`</span>.
        """
        return pulumi.get(self, "labels_all")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['outputs.VpcV1NetworkMetadata']:
        """
        :

           Metadata for the network resource.
           `metadata.parent_id` represents IAM container

        #### Inner value description

           Common resource metadata.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human readable name for the resource.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier of the parent resource to which the resource belongs.
        """
        return pulumi.get(self, "parent_id")

    @_builtins.property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> pulumi.Output[_builtins.float]:
        """
        :

           Version of the resource for safe concurrent modifications and consistent reads.
           Positive and monotonically increases on each resource spec change (but *not* on each change of the
           resource's container(s) or status).
           Service allows zero value or current.
        """
        return pulumi.get(self, "resource_version")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output['outputs.VpcV1NetworkStatus']:
        """
        Status of the network.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        :

           Timestamp indicating when the resource was last updated.

           A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
        """
        return pulumi.get(self, "updated_at")

