apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./fluxcd
  - ./kgateway
  - ./mimir
  - ./grafana
  - ./tempo
  - ./otel-collector
  - ./node-lifecycle-tracer
  - ./vllm
  - ./vllm-32b
