apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/open-webui/v0.11-v1/
