apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/vllm/v0.9-v1/
