apiVersion: v1
kind: Secret
metadata:
    name: airflow-admin-password
    namespace: airflow
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:QK6WVkXA1pkXvGYaKEip2LBar11dFqzVSYQbJosN0X9FK9iDN7bC0wXM4P/QZRVZ6YuXgt26IKtxFVO83tIxfdleCf9BqmyrzvwwFIg=,iv:Ciifw+dxxtxe4Tx9XvtGzYN5GpvDPhCAMvEdET4B5Ew=,tag:n2BvmsFSsGTjhecW1qGkvQ==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YnVXNGVEOEtuSm80Qllq
            RDBPNlNpZTQxeE5XeGl1R0dhZ21jbXFSMmpZClBSbXlPUFJjV09HeDhHUjNMME9Z
            UXMxa3kyaU14bm51Q3d4Y25XVmR0UDQKLS0tIDRYVFhXRkUyeng3L2tlR0k3MEhG
            bUxETnNjR29vR3NZeUZtQk9iTGM2QTgKpUQB0u+Ugsf0wDHIWjbP3cJ6iNoRve95
            dhYCv88tii9wFIpGXGXkuctOjsfCISRm5TJZr+nthrZjSA5NWuQJxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T18:30:24Z"
    mac: ENC[AES256_GCM,data:2qW9OI4apJWrtYXBA9iltPil/hTKTvJo63m8Hlx7pygl1+KfzhLSvCRk2bU0F3mWVq0+LKbqvg6PNTZvYuqbKWv4awv/8bIpzicM9PBgvrkIKBlpMVD4ysqq+HaLql7sT2/hRtRlBBLZ4OKaGYkmHmF5UVEE7a5Yjs9XM1kENvg=,iv:49Td661TCSz1lTxXqPNluC95Q9Oj/e8hcoLBvJej6JY=,tag:4MCJh8/ewYmCj6OnHs8TFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
