apiVersion: v1
kind: Secret
metadata:
    name: hf-token
    namespace: airflow
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:KDeiq+x96RsXdj1G6K9Dhlp1COudxEdKYtSJl9KPNp2h0o45OQ==,iv:7iGidpuZZbf/wVma6uXTYcIkn5wuEYNz2Xh1W080saM=,tag:wKSyVy4hGBhwz767B+OHkw==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraW10TUk4aXBYWko5Rmha
            UkhXVFNmV1k3V0ZTalJHaGtLc1JsdHk0WUVRClY2ekJ0WEhNSTBqUjdQL0c5MVEx
            ekE1RnM2anc1R2N2RGpRaXcrNm9SdzgKLS0tIEc5amY2WXJuNndnd3d3aVVqUkJm
            eklvWXJEdEE3RkRRN1VLUHRmcHg5R1UKJdVnm2ODjXh82ge4dnnoW1PsBZLf+rj0
            aVgWxw4OYyyWC6eud91vVw7ecXFQ8LeQ9qOT5M5lScfhViPxyRJkaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T18:59:34Z"
    mac: ENC[AES256_GCM,data:jgy+dxQ3mPoqJOMtKYHcqQMQDWAbUc1hmWzDoEl+nlKTl/brNZ60TkpOHssWWTVAHwSLwF/BWiGQfCmwU7ZYMWkR8hQ35Rq454vv/uPYZMnL7fBM4bcwzSziHWX7UXJKxkRwaS6ty27gfnFrN8g61WznjUqK0B8OBKUAqBLkgQc=,iv:nKEny9hutJznQBXe1dQJIKRhGwGOft4cdBDiAkzE2Pc=,tag:bCjYM+BNwGW6Z2fzw5MdWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
