apiVersion: v1
kind: Secret
metadata:
    name: hf-token
    namespace: airflow
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:lRh6QN0MG5DCEttnuZAyAUg0AOESmYzCfb3l6ARaZeu6be6lBg==,iv:hAYPXLv77dvBDi6EHAy8Ro1oTQHuWB1PvHPNwNNLWuI=,tag:gOaoUa1Eg8bOUKMa6fk1Fg==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSnFUQzVheHF3dUx2dTV1
            VVA0VmI0S011OXZMS292Titad2lDYmJSOGw4CmI2Z3hrK2UyL2NTMWRyOE5rZjBj
            MjZ0SnQzMjBKOENYRVZSUzVHdnpXRncKLS0tIDFNRXBsMTlkenRqT3lhV3FoeStF
            ZEtLNTVTQlhCZVR3d1RaNnVNaDljQVEKcYt1K2qjDpoPREJ4dlWm+viKiCDbzKCG
            dkeSoZ9dtoz0gv8Q1x4QJW47NK7BpsFZAGa5dDapS2wNs286VT69gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T19:05:06Z"
    mac: ENC[AES256_GCM,data:MB28Ih2/XDyaK269yUpyX77rOSA4CPHZPeJ/Juhd3dr4DXU2uNcBDAaeV6A12G9YCuCz59sC2kaRdkz+QdRbeFdesb9+6BJAgAfiXNx+o2bSAYTCYookfXRpl14MkQCutKc7O1YtyjU3SLLLO7aVvqtynZFdI5h5hYUlIFigdFI=,iv:P12JpFJ/z99ee59Zx7UqTw6hcjgKndOt/9TLqAgRdjo=,tag:n6W+56kpLl8Xxw26CmH4GQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
