apiVersion: v1
kind: Secret
metadata:
    name: hf-token
    namespace: airflow
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:wpN8Fu6Z2YhN2hQTZ3PFpOhQOe9dU0fLmOvkNPEeacrWXRuE4iT8j8NOp0GbKRU=,iv:NE+eiqhzRR6Pzf8UZZmncx5cF5kJwACCIsWtBJ9rNOg=,tag:5NWW8UfrII3cGZJUHYK5ag==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNWtBKzZiSVdPYjVPZUps
            YVBVNGNkdmMyNVc2c2tmZWdBaVFoYTJ2N1UwClV5MTloaU9PVlRZdUxVQWcyTXNi
            OEsvRWpJSjJ3aklyYnZ2MklvTXpobFEKLS0tIG53NUtUQ3RqOXpNcmdJMFV4SXdi
            VmE2Z25yelBkeTk3NmdLaDUvQXNUTFEK92V06W+A0c7ba8ljL9KFLKUrRbUQOfqX
            E021lnotXol8EFBxw25B94QAS26MZZSLR1NvBMXa9E4RVnNGNa9TUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T18:51:12Z"
    mac: ENC[AES256_GCM,data:wBtJswI6umagkuUwCNMB01sTXU5BYNWsexOlxiNCJjfafBt+FYEaSAqC9Rk5SY9srcG0W5G7FQ/PTjubsrkXLC+GHWHUsqh+f8cPpwDCsczZQEjvZZoqYM5tLBGRmlCA21Oi9JOvisWfG1/59hkZmk1eIG22jUWE0VAlrtgOTA4=,iv:Dt7HLyl6vW7y7gJFKU25f+o7Jo3zZYXTX6Uw0YrUqHw=,tag:DphvvlXR2JyWADs6oOEH0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
