apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-lifecycle-tracer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-lifecycle-tracer
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get]
  - apiGroups: [""]
    resources: [pods]
    verbs: [list]
  - apiGroups: [""]
    resources: [events]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-lifecycle-tracer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-lifecycle-tracer
subjects:
  - kind: ServiceAccount
    name: node-lifecycle-tracer
