# Management cluster configuration.
cluster_name: scw-mgmt-alpha
kubernetes_version: v1.34.3
scw_region: fr-par
control_plane_machine_type: DEV1-M
control_plane_machine_image: cluster-api-ubuntu-2404-v1.34.3
control_plane_count: 3
pod_cidr_range: 192.168.0.0/16
service_cidr_range: 10.96.0.0/12
private_network_cidr: 172.16.0.0/22
enable_cilium: true
enable_coredns: true
enable_flux: true
environment: production
project: scw-mgmt-alpha
flux_git_url: https://github.com/hrishin/kube-clusters
flux_git_branch: main
flux_git_path: clusters/scw-mgmt-alpha/extensions
flux_git_secret_name: flux-system
flux_git_secret_values_path: config/config.enc.yaml
flux_sops_secret_name: sops-age
flux_git_interval: 1m0s
flux_kustomization_interval: 10m0s

node_groups:
  core:
    commercial_type: DEV1-M
    machine_image: cluster-api-ubuntu-2404-v1.34.3
    desired_size: 1
    min_size: 1
    max_size: 2
    disk_size: 20
    labels:
      node-type: "core"
      workload: "system"
      environment: "production"
    taints:
      - key: "node-type"
        value: "core"
        effect: "NoSchedule"
