[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "pulumi_nebius"
version = "0.6.35"
description = "Pulumi provider for Nebius AI Cloud"
license = { text = "Apache-2.0" }
requires-python = ">=3.8"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "semver>=2.8.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pulumi_nebius*"]
