github:
    username: ENC[AES256_GCM,data:oauuLVghuA==,iv:uMgviCI90l54PAJRStyldkYHmQ691A0ArS/c/hKsCBE=,tag:wOoUfXSPaHbEOH0xi/eoTA==,type:str]
    token: ENC[AES256_GCM,data:VfzwMAdF4vUjnKGOx+3c+xf0P5Zhrpfuz9rxNHn5gAWwseSn7owha3wqWfLMkVR5fBBUAlQL3qGdDGFTZt8hiqnttxO7Geo0YIaI/W4P7vIlUkpY62j+B5bn3UP4,iv:wIdCXBeIFa0knA4JA8XDA0KryR0ZBICZy9AF2XtHXac=,tag:qheW+sV5iqwnE/c/lZMiDg==,type:str]
scale-away:
    access_key: ENC[AES256_GCM,data:lD8yV24=,iv:H4sLvzTaexTQXIH8MBklzJ/3pei7dRZn7NmDqgRXV2E=,tag:29CF/rHdzNmGRfARz71f5A==,type:str]
    secrete_key: ENC[AES256_GCM,data:2mMM0Q==,iv:7QPO00xPpp2f3qNxZ5IeUAWWYIbFA8c+UMzVRU4GaP0=,tag:2ebq/tl8X3g6ubOEbPrD8g==,type:str]
hf:
    token: ENC[AES256_GCM,data:Qt3in3ZS+kzr/gmVMgPKcuB1h9IHhm1g+LeCZbx5IGjErZQl7g==,iv:c0I9WVZhOvcRFx8xvPNH7RvFcQYUAqa/t7sxNxb6iZ0=,tag:Wjz+iNnYWyh99O4vUkGBfw==,type:str]
nebius:
    account_id: ENC[AES256_GCM,data:5imy3cJddPkWQrYiC+6dUWU9clviB+O4Kiy5OMSVMRTY,iv:0rKAEdMlz5Vb9s0z9CXnqrDXhconkMdmzzNSA+1BpWw=,tag:Q829YRZmN9SxFc8775WTdA==,type:str]
    public_key_id: ENC[AES256_GCM,data:tAGsPBP303p3bAWx8Zc/6Buj6o7J1zq1fp6N+w==,iv:xqFWmziOrqWtcNKINzV1U5nPgrzR5Z9J9aQ/1UUUtMs=,tag:4zOkD0XBf3SQE7Yahi+wHw==,type:str]
    private_key_file: ENC[AES256_GCM,data:MeJKKQ8poYJPMWbPaTvke0bGDkKL08WY1W4nCiS+rA==,iv:EBuzpzaZxaG0zPfLbFn7TilMb3FtS2WbEzB35TW5L9A=,tag:pjIfJWjt0kRCbSWsNWpaog==,type:str]
cf:
    api-key: ENC[AES256_GCM,data:UfgAT1Wa/wDkpqU99jXAYxs57Ph97/psEqPFaoHFmwB2Brx6bdQ//qfP+LNkFdiINuubdus=,iv:GN2G0/Sx4vosRRTeKGX3DNR+CzT3RSrbrQWMgIJ43QQ=,tag:z5ymqecmPSfiCeLsoGPLhA==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VHdMc0tNaXBTRXRkMDlV
            dlI4STlVQWo4dW1UZ282R2hNUU12TVZGdFJ3CmFlOHVoMDR6bzRsYVN3WjJxK2J4
            VUhJdHIwY0VQNmpockFDdUV5M0djQTgKLS0tIG5ocHF4U0tKTHVvOWUweFBYR0h3
            S1R4TVlGOHAvelZyTG45ZStMdWM2eWsKZZNqQxAczYwiLI5W/aA8iIYKg3xN6dzp
            PKBwK0XUeJiVEhhXcc1DefrwpgTjJEO8Dsyd9u/ovLHbcjl2lKBB1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T16:46:02Z"
    mac: ENC[AES256_GCM,data:rT/JtUMlrjssjnEfrTUycDKx5H82lbP1H4iyIxVBlurOT7K6YLcXwwUt7AylgWsl1ZMQX+17HUO1CpEUgexIejWYsBOcUpLj5A4rCqA1WE2sD2LaHnWvSe0q6aErHdHuJuqr2Gcd9XAZC5oS1LmsP/a3OVCkLb8skb2IQF1/z5w=,iv:J9Qlg8NgTLiBV36K8PU/nhYy7u4DehMe7YpubFiFbrU=,tag:7IDXqMUJ4NlsOoLVr98LgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
