github:
    username: ENC[AES256_GCM,data:7evmJ3X/VA==,iv:8vnk1tAGTPAiiXBp2kVuzKMhdPzUaqF3l7dnmUhC2ns=,tag:GvVxRZ4Sh4nLtZtKdSiLEA==,type:str]
    token: ENC[AES256_GCM,data:Z3ecineq+ABGDKQpWP6RnbWmruppKPb1vKYE4xBxbNviz4yP3nKTqw==,iv:Ja/pnN9Xvi7K+CKqCEtcmELwQCKkK2w6yrCaa7C9qBk=,tag:Y+T+Junf5pc5iPTy1LVKgw==,type:str]
scale-away:
    access_key: ENC[AES256_GCM,data:tIVD5Y/29ByEYYI93hDPS2tY28U=,iv:nE28mxOUQQ3FQO7RiFXzSOOCLSbDsui755LT8D0KCKI=,tag:K2v+31bVtYhRnsm4EM2SOA==,type:str]
    secrete_key: ENC[AES256_GCM,data:0L7582DWgzeSlgxw3nF9pYO05tb51fJLy+7D6NOeuAgmSGun,iv:BhkqkQLE3sVP/Q7Kwj1a70T95jxsF6Cn8zwgHfTuJfo=,tag:tHTQbkoa8IYNvuVbTn865Q==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeWNVbFo2OUorMXo5aWRw
            OWJXNnJKNG9yYUh4bkJLNFhkV3FKbWt1MlcwCldMT3E0VzRSdlYvaVphcTZUL29I
            cGYvem01c2hTcWNTbGdERUs0a1g2cFkKLS0tIGR3S3BPU0tLK2t4RFJ5ektCMUkw
            cjIrVHNscTRFT2lkY2k3NzJWd0FtMGcKLH/hMG+xsBNBoBHl9/Y8fDx8n2x/1OO0
            ufyqh46bTGSy8KwxCHoRLlsdiejrE5WDaNJpk414NpSgiNomI3/3dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T07:09:52Z"
    mac: ENC[AES256_GCM,data:drX589yJogfml1BMJfpJ9bHAhJOisij0MuRhV16+OGPXLBBA8w4YSeVaZiyZbejuv/TlOyVuHva777IMGXHpE12cewg/O36jptqZbCZs63W1m56TlvTVLP0L2jlwWuhwGzZKtaMz+nt6FfIm7lz0kwH2NBtBCv59kgNBzw1YFtY=,iv:Y/cILox9ER10QyWltL3S5NzV55ljl5THIwbqkYNVFAE=,tag:8MPeiVBqr+r/ru5Q4wOF1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
