apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:3pOISyi7JKCksvekB4xQ9uS4bMkJi+HGMFRWbA5KhXvKniNpeii2d4lx1OH3xRtf+XYFf70=,iv:/kZ7l1glxYkTvuqEtq0QTWKyvLV4rLJSmasWO4YfD2U=,tag:1cSEGd39XcO/CNJHmN/8Ig==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadS9ManlaYWdLaUlyemhl
            a3NhN0kzazhpVnpkMjN6YWM1WTg4MHRSNlVZClZ4eHB5VGc2bGtJQ0ozZVl3aGRT
            NVFzREVsN0E4SmdqVGhyQWJaWHlDM28KLS0tIFdxQm9ZcnFVczJXTHhBWjR1T0NW
            MUJsK2hjMnNxMlF1bE1UYWY2d2EvMXMKsj8UA2nmDB70rR23kglbKvBa0gRV4JwZ
            qVd0R0JlDPQDn8/UAZP1CJP+UYK4Y0UzwUEE+Yuewd/N/hlIGNUYuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T17:41:22Z"
    mac: ENC[AES256_GCM,data:tDOgYK4u+I4KVARyfow7yrEdPUxrRoDK/e//K4HcFD6IqPYdNBBuHwj6W3v2l3tq8vuZuKnQxZKToHIj7ayw7hDquFTgHsL4vqgs/luiCvnhiPCKOwBoHCQS2YUTlX0WtxLEd2APXOIeAyO63JLfWdGrQY/fk2yTQZxui2pPNxA=,iv:/codviDnCr5DvVodpqX5ujpSIdWqLAxVBnpsbqJWehc=,tag:w0KpDDrybBv1mHBSJDC/WA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
