apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:QRO3omL2OA17iHjlmOp6m3lWok26c2gx1QfEjts1soBMXnjt5YGxICnEBfqnUU68mkquYlw=,iv:Jvi9csjidr+uasKOE4IwzA7O/o+GJgGjKRgSR/ptq3k=,tag:jPzJE72am4IZtlYGbVD0lg==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRTlobGUyZWlUdHhGSGgz
            NnpPM09rUDY4S0RuTW14ZGdNSnlDY1NqaGdZCkdES1NrSndZSS9rMk94Yng4WHV0
            enl0UGU0SUplV3lOamxnQjM0VlFoalUKLS0tIExjUzNnTXdKbFNQZ1FHTGtTUkJG
            anA3UDlCOGJJY1BDOEF2WjFVMk5FQ2sKctJJq5dBXExsRpPAqL7VNzLjWj/IQvEA
            LYZSRgSxSQ4GaE3Rki5mFA+lnU/2rUPWD7dHCaoKF2Xt6/dqS8A98A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T09:32:01Z"
    mac: ENC[AES256_GCM,data:CnmB1zUOCdnAtn02Z3YLT44MemQx25g5tyOSvRnDnPgyIIxW2V/AvMBPET7rY2j3KuxAtCxzbPeaP4lJwWALmwFEr5+9+Zb06dUasjXuxvW39Q3ujqPIv6lVknMzQYGN+gqcyFN2g6v3D7LI71V+boT+v9zO1Hoh+xP5VV01r7I=,iv:zH5krsbkOvO/ch81IN3UsXU7WcRKEfm65TduT2qqDdo=,tag:pwc2N9/kWJvkAL4R5ixEBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
