apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ../../../../iac-modules/extensions/crds/kgateway/v2.3.0/
  - ../../../../iac-modules/extensions/crds/kube-prometheus-stack/v88.2.0/
