apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mimir
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/mimir/v2.14.0-v1/
