apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tracer
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/node-lifecycle-tracer/v1/
