apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lws-system
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/lws/v0.9.0-v1/
