apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    # Scaleway private networks are L2 VLANs -- native routing works.
    autoDirectNodeRoutes: true
    bpf:
      datapathMode: veth
    enableIPv6Masquerade: false
    # ipv4NativeRoutingCIDR must match the private_network_cidr in Pulumi config
    # so that Cilium knows which traffic to route natively vs masquerade.
    ipv4NativeRoutingCIDR: "172.16.0.0/22"
    # kubeadm control-plane default (EKS uses 443)
    k8sServicePort: 6443
    loadBalancer:
      mode: hybrid
    routingMode: native
