apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: "1.18.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  interval: 2m
  values:
    bpf:
      masquerade: true
    cluster:
      name: "${CLUSTER_NAME}"
    enableIPv4Masquerade: true

    hubble:
      enabled: true
      relay:
        enabled: true
        tolerations:
          - effect: NoSchedule
            key: node-type
            operator: Equal
            value: core
      ui:
        enabled: true
        tolerations:
          - effect: NoSchedule
            key: node-type
            operator: Equal
            value: core
    tolerations:
      - operator: Exists

    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
          - 192.168.0.0/16
        clusterPoolIPv4MaskSize: 24

    k8sServiceHost: "${CLUSTER_ENDPOINT}"
    kubeProxyReplacement: true
    loadBalancer:
      algorithm: maglev
    nodePort:
      enabled: true

    operator:
      prometheus:
        enabled: true
      replicas: 1
      tolerations:
        - effect: NoSchedule
          key: node-type
          operator: Equal
          value: core
    prometheus:
      enabled: true
