// pulumi-resource-nebius is the Pulumi provider binary.
// Pulumi exec's this binary for every resource Create/Read/Update/Delete
// operation. It must be installed at:
//
//	~/.pulumi/plugins/resource-nebius-v{VERSION}/pulumi-resource-nebius
//
// Install with: make install
package main

import (
	"github.com/hrishin/pulumi-nebius/provider"
	tfbridge "github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge"
)

func main() {
	tfbridge.Main("nebius", provider.ProviderVersion, provider.Provider(), pulumiSchema)
}

// pulumiSchema is the schema.json embedded at build time via go:embed.
// Generated by: make generate  (runs pulumi-tfgen-nebius)
//
//go:generate go run ./cmd/pulumi-tfgen-nebius all --out sdk/
var pulumiSchema []byte
